//! Frozen, reviewable command surface for the Rust CLI.

#![allow(clippy::too_many_lines)]

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct FlagSpec {
    pub name: &'static str,
    pub kind: &'static str,
    pub default: &'static str,
    pub usage: &'static str,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq)]
pub struct CommandSpec {
    pub path: &'static str,
    pub use_line: &'static str,
    pub short: &'static str,
    pub long: &'static str,
    pub hidden: bool,
    pub args_required: bool,
    pub positionals: &'static [&'static str],
    pub flags: &'static [FlagSpec],
}

pub fn all() -> Vec<CommandSpec> {
    vec![
        CommandSpec {
            path: "",
            use_line: "symeraseme",
            short: "Automated data broker removal tool",
            long: "symeraseme is the Go-port command-line entrypoint of Symaira EraseMe. The CLI vocabulary is settled in docs/mcp-contract.md §5; commands land as their port issues are implemented.",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[FlagSpec {
                name: "version",
                kind: "bool",
                default: "false",
                usage: "version for symeraseme",
            }],
        },
        CommandSpec {
            path: "auto-confirm",
            use_line: "auto-confirm REQUEST_ID",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &["REQUEST_ID"],
            flags: &[
                FlagSpec {
                    name: "dry-run",
                    kind: "bool",
                    default: "false",
                    usage: "Preview without clicking",
                },
                FlagSpec {
                    name: "headed",
                    kind: "bool",
                    default: "false",
                    usage: "Run browser in headed mode",
                },
                FlagSpec {
                    name: "request-id",
                    kind: "int",
                    default: "0",
                    usage: "Removal request ID",
                },
                FlagSpec {
                    name: "screenshot-dir",
                    kind: "string",
                    default: "",
                    usage: "Directory for screenshots",
                },
            ],
        },
        CommandSpec {
            path: "brokers",
            use_line: "brokers",
            short: "brokers commands",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "brokers list",
            use_line: "list",
            short: "List brokers",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "include-disabled",
                    kind: "bool",
                    default: "false",
                    usage: "include disabled brokers",
                },
                FlagSpec {
                    name: "include-inactive",
                    kind: "bool",
                    default: "false",
                    usage: "include inactive brokers",
                },
                FlagSpec {
                    name: "jurisdiction",
                    kind: "string",
                    default: "",
                    usage: "jurisdiction filter",
                },
                FlagSpec {
                    name: "law",
                    kind: "string",
                    default: "",
                    usage: "law filter",
                },
                FlagSpec {
                    name: "priority",
                    kind: "string",
                    default: "",
                    usage: "priority filter",
                },
                FlagSpec {
                    name: "status",
                    kind: "string",
                    default: "active",
                    usage: "status filter",
                },
            ],
        },
        CommandSpec {
            path: "brokers show",
            use_line: "show BROKER_ID",
            short: "Show one broker",
            long: "",
            hidden: false,
            args_required: true,
            positionals: &["BROKER_ID"],
            flags: &[],
        },
        CommandSpec {
            path: "calendar",
            use_line: "calendar",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "campaign",
                    kind: "string",
                    default: "",
                    usage: "Filter by campaign identifier",
                },
                FlagSpec {
                    name: "campaign-id",
                    kind: "string",
                    default: "",
                    usage: "Filter by campaign identifier",
                },
                FlagSpec {
                    name: "weeks",
                    kind: "int",
                    default: "4",
                    usage: "Number of weeks to look ahead",
                },
            ],
        },
        CommandSpec {
            path: "classify-reply",
            use_line: "classify-reply REQUEST_ID",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &["REQUEST_ID"],
            flags: &[
                FlagSpec {
                    name: "model",
                    kind: "string",
                    default: "",
                    usage: "LLM model override",
                },
                FlagSpec {
                    name: "provider",
                    kind: "string",
                    default: "",
                    usage: "LLM provider override",
                },
                FlagSpec {
                    name: "request-id",
                    kind: "int",
                    default: "0",
                    usage: "Removal request ID",
                },
                FlagSpec {
                    name: "save",
                    kind: "bool",
                    default: "true",
                    usage: "Save classification to database",
                },
            ],
        },
        CommandSpec {
            path: "completion",
            use_line: "completion [bash|zsh|fish|powershell]",
            short: "Generate shell completion scripts",
            long: "",
            hidden: false,
            args_required: true,
            positionals: &["[bash|zsh|fish|powershell]"],
            flags: &[],
        },
        CommandSpec {
            path: "config",
            use_line: "config",
            short: "config commands",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "config show",
            use_line: "show",
            short: "Show effective configuration",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[FlagSpec {
                name: "output",
                kind: "string",
                default: "text",
                usage: "output format: text or json",
            }],
        },
        CommandSpec {
            path: "dashboard",
            use_line: "dashboard",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "events",
            use_line: "events",
            short: "events commands",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "events show",
            use_line: "show REQUEST_ID",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &["REQUEST_ID"],
            flags: &[
                FlagSpec {
                    name: "after-event-id",
                    kind: "int",
                    default: "0",
                    usage: "Only return events with ID greater than this",
                },
                FlagSpec {
                    name: "request-id",
                    kind: "int",
                    default: "0",
                    usage: "Removal request ID",
                },
            ],
        },
        CommandSpec {
            path: "generate-dashboard",
            use_line: "generate-dashboard",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "auto-open",
                    kind: "bool",
                    default: "false",
                    usage: "Open dashboard in browser after generation",
                },
                FlagSpec {
                    name: "auto-refresh",
                    kind: "int",
                    default: "0",
                    usage: "Auto-refresh interval in seconds (0 = disabled)",
                },
                FlagSpec {
                    name: "open",
                    kind: "bool",
                    default: "false",
                    usage: "Open dashboard in browser after generation",
                },
                FlagSpec {
                    name: "output",
                    kind: "string",
                    default: "report.html",
                    usage: "Output file path",
                },
            ],
        },
        CommandSpec {
            path: "generate-rebuttal",
            use_line: "generate-rebuttal REQUEST_ID",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &["REQUEST_ID"],
            flags: &[
                FlagSpec {
                    name: "model",
                    kind: "string",
                    default: "",
                    usage: "LLM model override",
                },
                FlagSpec {
                    name: "provider",
                    kind: "string",
                    default: "",
                    usage: "LLM provider override",
                },
                FlagSpec {
                    name: "request-id",
                    kind: "int",
                    default: "0",
                    usage: "Removal request ID",
                },
                FlagSpec {
                    name: "save",
                    kind: "bool",
                    default: "true",
                    usage: "Save rebuttal to database",
                },
            ],
        },
        CommandSpec {
            path: "generate-report",
            use_line: "generate-report",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "all",
                    kind: "bool",
                    default: "false",
                    usage: "Include all campaigns",
                },
                FlagSpec {
                    name: "all-campaigns",
                    kind: "bool",
                    default: "false",
                    usage: "Include all campaigns",
                },
                FlagSpec {
                    name: "campaign-id",
                    kind: "string",
                    default: "",
                    usage: "Campaign identifier",
                },
                FlagSpec {
                    name: "format",
                    kind: "string",
                    default: "html",
                    usage: "Report format",
                },
                FlagSpec {
                    name: "output",
                    kind: "string",
                    default: "",
                    usage: "Output file path",
                },
            ],
        },
        CommandSpec {
            path: "generate-scheduler",
            use_line: "generate-scheduler",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "dry-run",
                    kind: "bool",
                    default: "false",
                    usage: "Preview without writing files",
                },
                FlagSpec {
                    name: "output-dir",
                    kind: "string",
                    default: "",
                    usage: "Output directory for config files",
                },
                FlagSpec {
                    name: "platform",
                    kind: "string",
                    default: "",
                    usage: "Target platform (auto-detected if omitted)",
                },
                FlagSpec {
                    name: "poll-hours",
                    kind: "string",
                    default: "",
                    usage: "Comma-separated hours for inbox polling",
                },
                FlagSpec {
                    name: "project-dir",
                    kind: "string",
                    default: "",
                    usage: "Project directory path",
                },
                FlagSpec {
                    name: "symeraseme-bin",
                    kind: "string",
                    default: "",
                    usage: "Path to symeraseme binary",
                },
                FlagSpec {
                    name: "tick-hour",
                    kind: "int",
                    default: "10",
                    usage: "Hour to run tick engine",
                },
                FlagSpec {
                    name: "tick-minute",
                    kind: "int",
                    default: "0",
                    usage: "Minute to run tick engine",
                },
                FlagSpec {
                    name: "venv-activate",
                    kind: "string",
                    default: "",
                    usage: "Virtualenv activate script path",
                },
            ],
        },
        CommandSpec {
            path: "grant",
            use_line: "grant [COMMAND]",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &["[COMMAND]"],
            flags: &[
                FlagSpec {
                    name: "command",
                    kind: "string",
                    default: "execute",
                    usage: "Command to grant consent for",
                },
                FlagSpec {
                    name: "dry-run",
                    kind: "bool",
                    default: "false",
                    usage: "Preview without issuing or revoking",
                },
                FlagSpec {
                    name: "list",
                    kind: "bool",
                    default: "false",
                    usage: "List all active tokens",
                },
                FlagSpec {
                    name: "list-tokens",
                    kind: "bool",
                    default: "false",
                    usage: "List all active tokens",
                },
                FlagSpec {
                    name: "revoke",
                    kind: "string",
                    default: "",
                    usage: "Token value to revoke",
                },
                FlagSpec {
                    name: "revoke-all",
                    kind: "bool",
                    default: "false",
                    usage: "Revoke all active tokens",
                },
                FlagSpec {
                    name: "ttl",
                    kind: "int",
                    default: "86400",
                    usage: "Token time-to-live in seconds",
                },
            ],
        },
        CommandSpec {
            path: "help",
            use_line: "help [command]",
            short: "Help about any command",
            long: "Help provides help for any command in the application.\nSimply type symeraseme help [path to command] for full details.",
            hidden: false,
            args_required: false,
            positionals: &["[command]"],
            flags: &[],
        },
        CommandSpec {
            path: "init-profile",
            use_line: "init-profile",
            short: "Create or replace the encrypted identity profile",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "email",
                    kind: "string",
                    default: "",
                    usage: "Email address",
                },
                FlagSpec {
                    name: "full-name",
                    kind: "string",
                    default: "",
                    usage: "Full name",
                },
                FlagSpec {
                    name: "profile",
                    kind: "string",
                    default: "",
                    usage: "Identity profile path",
                },
            ],
        },
        CommandSpec {
            path: "manual-tasks",
            use_line: "manual-tasks",
            short: "manual-tasks commands",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "manual-tasks cleanup",
            use_line: "cleanup",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[FlagSpec {
                name: "dry-run",
                kind: "bool",
                default: "false",
                usage: "Preview without deleting",
            }],
        },
        CommandSpec {
            path: "manual-tasks complete",
            use_line: "complete TASK_ID",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &["TASK_ID"],
            flags: &[
                FlagSpec {
                    name: "notes",
                    kind: "string",
                    default: "",
                    usage: "Completion notes",
                },
                FlagSpec {
                    name: "task-id",
                    kind: "int",
                    default: "0",
                    usage: "Manual task ID",
                },
            ],
        },
        CommandSpec {
            path: "manual-tasks list",
            use_line: "list",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "request-id",
                    kind: "int",
                    default: "0",
                    usage: "Filter by request ID",
                },
                FlagSpec {
                    name: "status",
                    kind: "string",
                    default: "",
                    usage: "Filter by task status",
                },
            ],
        },
        CommandSpec {
            path: "manual-tasks show",
            use_line: "show TASK_ID",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &["TASK_ID"],
            flags: &[FlagSpec {
                name: "task-id",
                kind: "int",
                default: "0",
                usage: "Manual task ID",
            }],
        },
        CommandSpec {
            path: "mcp",
            use_line: "mcp",
            short: "Run the MCP JSON-RPC interface",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "allow-remote",
                    kind: "bool",
                    default: "false",
                    usage: "allow non-loopback HTTP binds",
                },
                FlagSpec {
                    name: "host",
                    kind: "string",
                    default: "127.0.0.1",
                    usage: "MCP HTTP bind host",
                },
                FlagSpec {
                    name: "port",
                    kind: "int",
                    default: "8000",
                    usage: "MCP HTTP bind port",
                },
                FlagSpec {
                    name: "stdio",
                    kind: "bool",
                    default: "false",
                    usage: "use newline-delimited JSON-RPC on stdin/stdout",
                },
            ],
        },
        CommandSpec {
            path: "migrate",
            use_line: "migrate",
            short: "Migrate a Python-era installation to the Go layout",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "backup",
                    kind: "string",
                    default: "",
                    usage: "backup directory (default: <destination>.migration-backup)",
                },
                FlagSpec {
                    name: "binary",
                    kind: "string",
                    default: "",
                    usage: "absolute symeraseme binary path for generated schedules",
                },
                FlagSpec {
                    name: "copy-secrets",
                    kind: "bool",
                    default: "false",
                    usage: "copy secrets through an injected SecretStore (never enabled by default)",
                },
                FlagSpec {
                    name: "destination",
                    kind: "string",
                    default: "",
                    usage: "separate Go destination directory (required)",
                },
                FlagSpec {
                    name: "destination-config",
                    kind: "string",
                    default: "",
                    usage: "optional separate Go config/profile directory",
                },
                FlagSpec {
                    name: "dry-run",
                    kind: "bool",
                    default: "false",
                    usage: "report detected items without creating backups or changing files",
                },
                FlagSpec {
                    name: "home",
                    kind: "string",
                    default: "",
                    usage: "synthetic or operator-selected home for native scheduler units",
                },
                FlagSpec {
                    name: "json",
                    kind: "bool",
                    default: "false",
                    usage: "write the migration report as JSON",
                },
                FlagSpec {
                    name: "platform",
                    kind: "string",
                    default: "",
                    usage: "scheduler platform: cron, launchd, or systemd",
                },
                FlagSpec {
                    name: "project-dir",
                    kind: "string",
                    default: "",
                    usage: "project directory for generated schedule wrappers",
                },
                FlagSpec {
                    name: "source",
                    kind: "string",
                    default: "",
                    usage: "Python-era installation data/config directory (required)",
                },
                FlagSpec {
                    name: "source-config",
                    kind: "string",
                    default: "",
                    usage: "optional separate Python config/profile directory",
                },
            ],
        },
        CommandSpec {
            path: "plan",
            use_line: "plan",
            short: "plan commands",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "plan create",
            use_line: "create",
            short: "Create a removal campaign plan",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "campaign",
                    kind: "string",
                    default: "",
                    usage: "campaign identifier",
                },
                FlagSpec {
                    name: "category",
                    kind: "string",
                    default: "",
                    usage: "category filter",
                },
                FlagSpec {
                    name: "include-inactive",
                    kind: "bool",
                    default: "false",
                    usage: "include inactive brokers",
                },
                FlagSpec {
                    name: "jurisdiction",
                    kind: "string",
                    default: "",
                    usage: "jurisdiction filter",
                },
                FlagSpec {
                    name: "law",
                    kind: "string",
                    default: "",
                    usage: "law filter",
                },
                FlagSpec {
                    name: "max",
                    kind: "int",
                    default: "30",
                    usage: "maximum brokers",
                },
                FlagSpec {
                    name: "notes",
                    kind: "string",
                    default: "",
                    usage: "campaign notes",
                },
                FlagSpec {
                    name: "priority",
                    kind: "string",
                    default: "",
                    usage: "priority filter",
                },
                FlagSpec {
                    name: "profile",
                    kind: "string",
                    default: "",
                    usage: "identity profile path",
                },
                FlagSpec {
                    name: "status",
                    kind: "string",
                    default: "active",
                    usage: "broker status filter",
                },
            ],
        },
        CommandSpec {
            path: "plan execute",
            use_line: "execute",
            short: "Execute planned requests",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "account",
                    kind: "string",
                    default: "",
                    usage: "email account name",
                },
                FlagSpec {
                    name: "batch-size",
                    kind: "int",
                    default: "5",
                    usage: "maximum requests to execute",
                },
                FlagSpec {
                    name: "campaign",
                    kind: "string",
                    default: "",
                    usage: "campaign identifier",
                },
                FlagSpec {
                    name: "consent",
                    kind: "string",
                    default: "",
                    usage: "consent token for destructive execution",
                },
                FlagSpec {
                    name: "consent-file",
                    kind: "string",
                    default: "",
                    usage: "path to consent token file",
                },
                FlagSpec {
                    name: "dry-run",
                    kind: "bool",
                    default: "false",
                    usage: "preview without sending",
                },
            ],
        },
        CommandSpec {
            path: "plan show",
            use_line: "show",
            short: "Show planned requests",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "campaign",
                    kind: "string",
                    default: "",
                    usage: "campaign identifier",
                },
                FlagSpec {
                    name: "status",
                    kind: "string",
                    default: "",
                    usage: "request status filter",
                },
            ],
        },
        CommandSpec {
            path: "plan status",
            use_line: "status",
            short: "Show campaign status",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "plan tick",
            use_line: "tick",
            short: "Run the deadline tick engine",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[FlagSpec {
                name: "dry-run",
                kind: "bool",
                default: "false",
                usage: "do not mutate requests",
            }],
        },
        CommandSpec {
            path: "poll-inbox",
            use_line: "poll-inbox",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "campaign-id",
                    kind: "string",
                    default: "",
                    usage: "Filter by campaign",
                },
                FlagSpec {
                    name: "folders",
                    kind: "string",
                    default: "",
                    usage: "IMAP folders to poll (default: ['INBOX']). Deduplicates by Message-ID across folders.",
                },
                FlagSpec {
                    name: "host",
                    kind: "string",
                    default: "imap.gmail.com",
                    usage: "IMAP server hostname",
                },
                FlagSpec {
                    name: "oauth2-access-token",
                    kind: "string",
                    default: "",
                    usage: "IMAP OAuth2 access token or secret reference (never printed)",
                },
                FlagSpec {
                    name: "oauth2-username",
                    kind: "string",
                    default: "",
                    usage: "IMAP OAuth2 username (defaults to --username)",
                },
                FlagSpec {
                    name: "port",
                    kind: "int",
                    default: "993",
                    usage: "IMAP server port",
                },
                FlagSpec {
                    name: "since",
                    kind: "int",
                    default: "14",
                    usage: "Fetch messages from the last N days",
                },
                FlagSpec {
                    name: "since-days",
                    kind: "int",
                    default: "14",
                    usage: "Fetch messages from the last N days",
                },
                FlagSpec {
                    name: "ssl",
                    kind: "bool",
                    default: "true",
                    usage: "Use SSL/TLS connection",
                },
                FlagSpec {
                    name: "username",
                    kind: "string",
                    default: "",
                    usage: "IMAP username (email address)",
                },
            ],
        },
        CommandSpec {
            path: "registry",
            use_line: "registry",
            short: "registry commands",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "registry list",
            use_line: "list",
            short: "List registry brokers",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "registry validate",
            use_line: "validate",
            short: "Validate the broker registry",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "render-template",
            use_line: "render-template TEMPLATE",
            short: "Render a legal template",
            long: "",
            hidden: false,
            args_required: true,
            positionals: &["TEMPLATE"],
            flags: &[
                FlagSpec {
                    name: "broker-name",
                    kind: "string",
                    default: "",
                    usage: "Name of the data broker",
                },
                FlagSpec {
                    name: "broker-website",
                    kind: "string",
                    default: "",
                    usage: "Broker website URL",
                },
            ],
        },
        CommandSpec {
            path: "requests",
            use_line: "requests",
            short: "requests commands",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "requests list",
            use_line: "list",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "broker-id",
                    kind: "string",
                    default: "",
                    usage: "Filter by broker identifier",
                },
                FlagSpec {
                    name: "campaign-id",
                    kind: "string",
                    default: "",
                    usage: "Filter by campaign identifier",
                },
                FlagSpec {
                    name: "page",
                    kind: "int",
                    default: "1",
                    usage: "1-indexed page number",
                },
                FlagSpec {
                    name: "page-size",
                    kind: "int",
                    default: "100",
                    usage: "Maximum items per page",
                },
                FlagSpec {
                    name: "status",
                    kind: "string",
                    default: "",
                    usage: "Filter by request status",
                },
            ],
        },
        CommandSpec {
            path: "review",
            use_line: "review FILE",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &["FILE"],
            flags: &[FlagSpec {
                name: "path",
                kind: "string",
                default: "",
                usage: "The path to the file to redact",
            }],
        },
        CommandSpec {
            path: "run-web-form",
            use_line: "run-web-form BROKER_ID",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &["BROKER_ID"],
            flags: &[
                FlagSpec {
                    name: "broker-id",
                    kind: "string",
                    default: "",
                    usage: "Broker identifier",
                },
                FlagSpec {
                    name: "dry-run",
                    kind: "bool",
                    default: "false",
                    usage: "Preview without running",
                },
                FlagSpec {
                    name: "headed",
                    kind: "bool",
                    default: "false",
                    usage: "Run browser in headed mode (visible)",
                },
                FlagSpec {
                    name: "request-id",
                    kind: "int",
                    default: "0",
                    usage: "Optional removal request ID for manual task linking",
                },
                FlagSpec {
                    name: "screenshot-dir",
                    kind: "string",
                    default: "",
                    usage: "Directory for screenshots",
                },
            ],
        },
        CommandSpec {
            path: "schedule",
            use_line: "schedule",
            short: "schedule commands",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "schedule install",
            use_line: "install",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "dry-run",
                    kind: "bool",
                    default: "false",
                    usage: "Preview without installing",
                },
                FlagSpec {
                    name: "platform",
                    kind: "string",
                    default: "",
                    usage: "Target platform (auto-detected if omitted)",
                },
                FlagSpec {
                    name: "tick-hour",
                    kind: "int",
                    default: "10",
                    usage: "Hour to run tick engine",
                },
                FlagSpec {
                    name: "tick-minute",
                    kind: "int",
                    default: "0",
                    usage: "Minute to run tick engine",
                },
            ],
        },
        CommandSpec {
            path: "schedule status",
            use_line: "status",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[FlagSpec {
                name: "platform",
                kind: "string",
                default: "",
                usage: "Target platform (auto-detected if omitted)",
            }],
        },
        CommandSpec {
            path: "schedule uninstall",
            use_line: "uninstall",
            short: "",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[FlagSpec {
                name: "platform",
                kind: "string",
                default: "",
                usage: "Target platform (auto-detected if omitted)",
            }],
        },
        CommandSpec {
            path: "serve",
            use_line: "serve",
            short: "Run the MCP JSON-RPC interface",
            long: "",
            hidden: true,
            args_required: false,
            positionals: &[],
            flags: &[
                FlagSpec {
                    name: "allow-remote",
                    kind: "bool",
                    default: "false",
                    usage: "allow non-loopback HTTP binds",
                },
                FlagSpec {
                    name: "host",
                    kind: "string",
                    default: "127.0.0.1",
                    usage: "MCP HTTP bind host",
                },
                FlagSpec {
                    name: "port",
                    kind: "int",
                    default: "8000",
                    usage: "MCP HTTP bind port",
                },
                FlagSpec {
                    name: "stdio",
                    kind: "bool",
                    default: "false",
                    usage: "use newline-delimited JSON-RPC on stdin/stdout",
                },
            ],
        },
        CommandSpec {
            path: "show-profile",
            use_line: "show-profile",
            short: "Show the encrypted identity profile",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[],
        },
        CommandSpec {
            path: "status",
            use_line: "status",
            short: "Show campaign status",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[FlagSpec {
                name: "campaign",
                kind: "string",
                default: "",
                usage: "Campaign identifier",
            }],
        },
        CommandSpec {
            path: "tick",
            use_line: "tick",
            short: "Run the deadline tick engine",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[FlagSpec {
                name: "dry-run",
                kind: "bool",
                default: "false",
                usage: "do not mutate requests",
            }],
        },
        CommandSpec {
            path: "version",
            use_line: "version",
            short: "Show the installed Symaira EraseMe version",
            long: "",
            hidden: false,
            args_required: false,
            positionals: &[],
            flags: &[FlagSpec {
                name: "json",
                kind: "bool",
                default: "false",
                usage: "print the versionkit handshake payload (JSON)",
            }],
        },
    ]
}

pub fn find<'a>(specs: &'a [CommandSpec], path: &[&str]) -> Option<&'a CommandSpec> {
    let key = path.join(" ");
    specs.iter().find(|spec| spec.path == key)
}

pub fn children<'a>(specs: &'a [CommandSpec], path: &[&str]) -> Vec<&'a CommandSpec> {
    let prefix = path.join(" ");
    let depth = path.len() + 1;
    specs
        .iter()
        .filter(|spec| {
            let parts: Vec<&str> = spec.path.split_whitespace().collect();
            parts.len() == depth
                && (prefix.is_empty() || spec.path.starts_with(&(prefix.clone() + " ")))
        })
        .collect()
}
