use std::env;
use std::fs::{self, DirEntry};
use std::path::{Component, Path, PathBuf};

const EXPECTED_BROKERS: usize = 1_277;
const MAX_DIRECTORY_DEPTH: usize = 8;
const MAX_DIRECTORY_ENTRIES: usize = 16_384;
const MAX_BROKER_FILES: usize = 4_096;
const MAX_SELECTED_FILE_BYTES: u64 = 1 << 20;
const MAX_SELECTED_BYTES: u64 = 16 << 20;

#[derive(Default)]
struct CollectionBudget {
    directory_entries: usize,
    broker_files: usize,
    selected_bytes: u64,
}

struct SelectedFile {
    relative: String,
    source: PathBuf,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let registry = manifest_dir.join("../../registry");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("out dir"));
    println!("cargo:rerun-if-changed=../../registry");

    let mut files = Vec::new();
    let mut budget = CollectionBudget::default();
    collect(&registry, &registry, 0, &mut budget, &mut files).unwrap_or_else(|error| {
        panic!("registry embedding rejected: {error}");
    });
    files.sort_by(|left, right| left.relative.cmp(&right.relative));

    let broker_count = files
        .iter()
        .filter(|file| is_broker_file(&file.relative))
        .count();
    assert_eq!(
        broker_count, EXPECTED_BROKERS,
        "embedded broker corpus count drifted"
    );

    let mut generated = String::from("// @generated by symeraseme-core/build.rs\n");
    generated.push_str("pub static FILES: &[(&str, &[u8])] = &[\n");
    for file in files {
        let target = out_dir.join(&file.relative);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent).expect("create embedded asset directory");
        }
        fs::copy(&file.source, &target).expect("copy embedded registry asset");
        generated.push_str(&format!(
            "    ({:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{relative}\"))),\n",
            file.relative,
            relative = file.relative
        ));
    }
    generated.push_str("];\n");
    fs::write(out_dir.join("embedded_registry.rs"), generated)
        .expect("write embedded registry index");
}

fn collect(
    root: &Path,
    directory: &Path,
    depth: usize,
    budget: &mut CollectionBudget,
    files: &mut Vec<SelectedFile>,
) -> Result<(), String> {
    if depth > MAX_DIRECTORY_DEPTH {
        return Err(format!(
            "directory nesting exceeds {MAX_DIRECTORY_DEPTH} levels"
        ));
    }

    let metadata = fs::symlink_metadata(directory)
        .map_err(|error| format!("inspect {}: {error}", directory.display()))?;
    if metadata.file_type().is_symlink() || !metadata.file_type().is_dir() {
        return Err(format!(
            "registry directory is not a real directory: {}",
            directory.display()
        ));
    }

    let mut entries = Vec::new();
    for item in
        fs::read_dir(directory).map_err(|error| format!("read {}: {error}", directory.display()))?
    {
        let entry = item.map_err(|error| format!("read registry entry: {error}"))?;
        budget.directory_entries = budget
            .directory_entries
            .checked_add(1)
            .ok_or_else(|| "directory entry counter overflowed".to_owned())?;
        if budget.directory_entries > MAX_DIRECTORY_ENTRIES {
            return Err(format!(
                "directory entry limit {MAX_DIRECTORY_ENTRIES} exceeded"
            ));
        }
        entries.push(entry);
    }
    entries.sort_by_key(|left| left.path());

    for entry in entries {
        let file_type = entry
            .file_type()
            .map_err(|error| format!("inspect registry entry: {error}"))?;
        if file_type.is_symlink() {
            return Err(format!(
                "registry contains a symlink: {}",
                entry.path().display()
            ));
        }
        if file_type.is_dir() {
            collect(root, &entry.path(), depth + 1, budget, files)?;
            continue;
        }
        if !file_type.is_file() {
            return Err(format!(
                "registry entry is not a regular file: {}",
                entry.path().display()
            ));
        }

        let relative = relative_utf8(root, &entry)?;
        if !is_selected(&relative) {
            continue;
        }
        let metadata = fs::symlink_metadata(entry.path())
            .map_err(|error| format!("inspect {relative}: {error}"))?;
        let size = metadata.len();
        if size > MAX_SELECTED_FILE_BYTES {
            return Err(format!(
                "selected file {relative} exceeds {MAX_SELECTED_FILE_BYTES} bytes"
            ));
        }
        if is_broker_file(&relative) {
            budget.broker_files = budget
                .broker_files
                .checked_add(1)
                .ok_or_else(|| "broker file counter overflowed".to_owned())?;
            if budget.broker_files > MAX_BROKER_FILES {
                return Err(format!("broker file limit {MAX_BROKER_FILES} exceeded"));
            }
        }
        budget.selected_bytes = budget
            .selected_bytes
            .checked_add(size)
            .ok_or_else(|| "selected byte counter overflowed".to_owned())?;
        if budget.selected_bytes > MAX_SELECTED_BYTES {
            return Err(format!(
                "selected registry bytes exceed {MAX_SELECTED_BYTES}"
            ));
        }
        files.push(SelectedFile {
            relative,
            source: entry.path(),
        });
    }
    Ok(())
}

fn relative_utf8(root: &Path, entry: &DirEntry) -> Result<String, String> {
    let entry_path = entry.path();
    let relative = entry_path
        .strip_prefix(root)
        .map_err(|error| format!("registry path: {error}"))?;
    let mut components = Vec::new();
    for component in relative.components() {
        let Component::Normal(value) = component else {
            return Err(format!("invalid registry path: {}", relative.display()));
        };
        let value = value
            .to_str()
            .ok_or_else(|| format!("registry path is not UTF-8: {}", relative.display()))?;
        components.push(value);
    }
    if components.is_empty() {
        return Err("empty registry path".to_owned());
    }
    Ok(components.join("/"))
}

fn is_selected(relative: &str) -> bool {
    relative == "manifest.json"
        || relative == "schemas/broker.schema.json"
        || is_broker_file(relative)
}

fn is_broker_file(relative: &str) -> bool {
    if !relative.starts_with("brokers/") {
        return false;
    }
    let path = Path::new(relative);
    matches!(
        path.extension().and_then(|value| value.to_str()),
        Some("yaml" | "yml")
    ) && !path
        .file_name()
        .and_then(|value| value.to_str())
        .is_some_and(|name| name.starts_with('_'))
}
