use cap_fs_ext::{FollowSymlinks, OpenOptionsFollowExt};
use cap_std::ambient_authority;
use cap_std::fs::{Dir, File as CapFile, OpenOptions as CapOpenOptions};
use std::env;
use std::fs::{self, DirEntry, OpenOptions};
use std::io::{self, Read, Write};
use std::path::{Component, Path, PathBuf};

const EXPECTED_BROKERS: usize = 1_277;
const MAX_DIRECTORY_DEPTH: usize = 8;
const MAX_DIRECTORY_ENTRIES: usize = 16_384;
const MAX_BROKER_FILES: usize = 4_096;
const MAX_SELECTED_FILE_BYTES: u64 = 1 << 20;
const MAX_SELECTED_BYTES: u64 = 16 << 20;

#[derive(Default)]
struct CollectionBudget {
    directory_entries: usize,
    broker_files: usize,
    selected_bytes: u64,
}

struct SelectedFile {
    relative: String,
    source: CapFile,
    size: u64,
}

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let registry = manifest_dir.join("../../registry");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("out dir"));
    println!("cargo:rerun-if-changed=../../registry");

    let mut files = Vec::new();
    let mut budget = CollectionBudget::default();
    let registry_dir = Dir::open_ambient_dir(&registry, ambient_authority())
        .expect("open registry source directory");
    collect(
        &registry,
        &registry,
        &registry_dir,
        0,
        &mut budget,
        &mut files,
    )
    .unwrap_or_else(|error| panic!("registry embedding rejected: {error}"));
    files.sort_by(|left, right| left.relative.cmp(&right.relative));

    let broker_count = files
        .iter()
        .filter(|file| is_broker_file(&file.relative))
        .count();
    assert_eq!(
        broker_count, EXPECTED_BROKERS,
        "embedded broker corpus count drifted"
    );

    let mut generated = String::from("// @generated by symeraseme-core/build.rs\n");
    generated.push_str("pub static FILES: &[(&str, &[u8])] = &[\n");
    for file in files {
        let target = out_dir.join(&file.relative);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent).expect("create embedded asset directory");
        }
        copy_asset(file.source, file.size, &target).unwrap_or_else(|error| {
            panic!("copy embedded asset {}: {error}", file.relative);
        });
        let relative_literal = format!("{:#?}", file.relative);
        let include_path_literal = format!("{:#?}", format!("/{}", file.relative));
        generated.push_str(&format!(
            "    ({relative_literal}, include_bytes!(concat!(env!(\"OUT_DIR\"), {include_path_literal}))),\n"
        ));
    }
    generated.push_str("];\n");
    write_atomic(&out_dir.join("embedded_registry.rs"), generated.as_bytes())
        .expect("write embedded registry index");
}

fn collect(
    root: &Path,
    directory: &Path,
    root_dir: &Dir,
    depth: usize,
    budget: &mut CollectionBudget,
    files: &mut Vec<SelectedFile>,
) -> Result<(), String> {
    if depth > MAX_DIRECTORY_DEPTH {
        return Err(format!(
            "directory nesting exceeds {MAX_DIRECTORY_DEPTH} levels"
        ));
    }

    let metadata = fs::symlink_metadata(directory)
        .map_err(|error| format!("inspect {}: {error}", directory.display()))?;
    if metadata.file_type().is_symlink() || !metadata.file_type().is_dir() {
        return Err(format!(
            "registry directory is not a real directory: {}",
            directory.display()
        ));
    }

    let mut entries = Vec::new();
    for item in
        fs::read_dir(directory).map_err(|error| format!("read {}: {error}", directory.display()))?
    {
        let entry = item.map_err(|error| format!("read registry entry: {error}"))?;
        budget.directory_entries = budget
            .directory_entries
            .checked_add(1)
            .ok_or_else(|| "directory entry counter overflowed".to_owned())?;
        if budget.directory_entries > MAX_DIRECTORY_ENTRIES {
            return Err(format!(
                "directory entry limit {MAX_DIRECTORY_ENTRIES} exceeded"
            ));
        }
        entries.push(entry);
    }
    entries.sort_by_key(|left| left.path());

    for entry in entries {
        let file_type = entry
            .file_type()
            .map_err(|error| format!("inspect registry entry: {error}"))?;
        if file_type.is_symlink() {
            return Err(format!(
                "registry contains a symlink: {}",
                entry.path().display()
            ));
        }
        if file_type.is_dir() {
            let entry_path = entry.path();
            let relative = entry_path
                .strip_prefix(root)
                .map_err(|error| format!("registry path: {error}"))?;
            let components = relative.components().collect::<Vec<_>>();
            if components
                .first()
                .is_some_and(|value| value.as_os_str() == "brokers")
                && !(components.len() == 1
                    || (components.len() == 2
                        && components[1]
                            .as_os_str()
                            .to_str()
                            .is_some_and(|value| matches!(value, "eu" | "uk" | "us"))))
            {
                return Err(format!(
                    "invalid broker directory layout: {}",
                    relative.display()
                ));
            }
            collect(root, &entry_path, root_dir, depth + 1, budget, files)?;
            continue;
        }
        if !file_type.is_file() {
            return Err(format!(
                "registry entry is not a regular file: {}",
                entry.path().display()
            ));
        }

        let relative = relative_utf8(root, &entry)?;
        if relative.starts_with("brokers/")
            && !is_broker_file(&relative)
            && !is_doc_yaml_file(&relative)
        {
            return Err(format!("invalid broker file layout: {relative}"));
        }
        if !is_selected(&relative) {
            continue;
        }
        let metadata = fs::symlink_metadata(entry.path())
            .map_err(|error| format!("inspect {relative}: {error}"))?;
        let mut options = CapOpenOptions::new();
        options.read(true).follow(FollowSymlinks::No);
        let source = root_dir
            .open_with(Path::new(&relative), &options)
            .map_err(|error| format!("open {relative} without following symlinks: {error}"))?;
        let opened_metadata = source
            .metadata()
            .map_err(|error| format!("inspect opened {relative}: {error}"))?;
        if !opened_metadata.is_file() || opened_metadata.len() != metadata.len() {
            return Err(format!("source metadata changed before copy: {relative}"));
        }
        let size = opened_metadata.len();
        if size > MAX_SELECTED_FILE_BYTES {
            return Err(format!(
                "selected file {relative} exceeds {MAX_SELECTED_FILE_BYTES} bytes"
            ));
        }
        if is_broker_file(&relative) {
            budget.broker_files = budget
                .broker_files
                .checked_add(1)
                .ok_or_else(|| "broker file counter overflowed".to_owned())?;
            if budget.broker_files > MAX_BROKER_FILES {
                return Err(format!("broker file limit {MAX_BROKER_FILES} exceeded"));
            }
        }
        budget.selected_bytes = budget
            .selected_bytes
            .checked_add(size)
            .ok_or_else(|| "selected byte counter overflowed".to_owned())?;
        if budget.selected_bytes > MAX_SELECTED_BYTES {
            return Err(format!(
                "selected registry bytes exceed {MAX_SELECTED_BYTES}"
            ));
        }
        files.push(SelectedFile {
            relative,
            source,
            size,
        });
    }
    Ok(())
}

fn relative_utf8(root: &Path, entry: &DirEntry) -> Result<String, String> {
    let entry_path = entry.path();
    let relative = entry_path
        .strip_prefix(root)
        .map_err(|error| format!("registry path: {error}"))?;
    let mut components = Vec::new();
    for component in relative.components() {
        let Component::Normal(value) = component else {
            return Err(format!("invalid registry path: {}", relative.display()));
        };
        let value = value
            .to_str()
            .ok_or_else(|| format!("registry path is not UTF-8: {}", relative.display()))?;
        if value.contains('\\') || value.chars().any(char::is_control) {
            return Err(format!(
                "registry path contains control or backslash: {}",
                relative.display()
            ));
        }
        components.push(value);
    }
    if components.is_empty() {
        return Err("empty registry path".to_owned());
    }
    Ok(components.join("/"))
}

fn is_selected(relative: &str) -> bool {
    relative == "manifest.json"
        || relative == "schemas/broker.schema.json"
        || is_broker_file(relative)
}

fn is_doc_yaml_file(relative: &str) -> bool {
    let components = relative.split('/').collect::<Vec<_>>();
    components.len() == 3
        && components[0] == "brokers"
        && matches!(components[1], "eu" | "uk" | "us")
        && components[2].starts_with('_')
        && matches!(
            Path::new(components[2])
                .extension()
                .and_then(|value| value.to_str()),
            Some("yaml" | "yml")
        )
}

fn is_broker_file(relative: &str) -> bool {
    let components = relative.split('/').collect::<Vec<_>>();
    if components.len() != 3 || components[0] != "brokers" {
        return false;
    }
    if !matches!(components[1], "eu" | "uk" | "us") {
        return false;
    }
    let path = Path::new(components[2]);
    matches!(
        path.extension().and_then(|value| value.to_str()),
        Some("yaml" | "yml")
    ) && !components[2].starts_with('_')
}

fn copy_asset(mut source: CapFile, expected_size: u64, target: &Path) -> io::Result<()> {
    let opened_meta = source.metadata()?;
    if !opened_meta.is_file() || opened_meta.len() != expected_size {
        return Err(io::Error::new(
            io::ErrorKind::InvalidData,
            "source metadata changed before copy",
        ));
    }

    let temp = target.with_file_name(format!(
        ".{}.tmp",
        target
            .file_name()
            .and_then(|name| name.to_str())
            .unwrap_or("asset")
    ));
    let _ = fs::remove_file(&temp);
    let result = (|| {
        let mut output = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temp)?;
        let copied = io::copy(
            &mut (&mut source).take(MAX_SELECTED_FILE_BYTES + 1),
            &mut output,
        )?;
        if copied > MAX_SELECTED_FILE_BYTES || copied != expected_size {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "source grew or copied size differs from metadata",
            ));
        }
        output.flush()?;
        if source.metadata()?.len() != copied {
            return Err(io::Error::new(
                io::ErrorKind::InvalidData,
                "source size changed during copy",
            ));
        }
        drop(output);
        let _ = fs::remove_file(target);
        fs::rename(&temp, target)
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temp);
    }
    result
}

fn write_atomic(target: &Path, bytes: &[u8]) -> io::Result<()> {
    let temp = target.with_file_name(".embedded_registry.rs.tmp");
    let result = (|| {
        let mut output = OpenOptions::new()
            .write(true)
            .create_new(true)
            .open(&temp)?;
        output.write_all(bytes)?;
        output.flush()?;
        drop(output);
        fs::rename(&temp, target)
    })();
    if result.is_err() {
        let _ = fs::remove_file(&temp);
    }
    result
}
