use std::env;
use std::fs;
use std::path::{Path, PathBuf};

const EXPECTED_BROKERS: usize = 1_277;

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let registry = manifest_dir.join("../../registry");
    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("out dir"));
    println!("cargo:rerun-if-changed=../../registry");

    let mut files = Vec::new();
    collect(&registry, &registry, &mut files);
    files.sort_by(|left, right| left.0.cmp(&right.0));

    let broker_count = files
        .iter()
        .filter(|(relative, _)| {
            relative.starts_with("brokers/")
                && matches!(
                    Path::new(relative).extension().and_then(|v| v.to_str()),
                    Some("yaml" | "yml")
                )
                && !Path::new(relative)
                    .file_name()
                    .and_then(|v| v.to_str())
                    .is_some_and(|name| name.starts_with('_'))
        })
        .count();
    assert_eq!(
        broker_count, EXPECTED_BROKERS,
        "embedded broker corpus count drifted"
    );

    let mut generated = String::from("// @generated by symeraseme-core/build.rs\n");
    generated.push_str("pub static FILES: &[(&str, &[u8])] = &[\n");
    for (relative, source) in files {
        let target = out_dir.join(&relative);
        if let Some(parent) = target.parent() {
            fs::create_dir_all(parent).expect("create embedded asset directory");
        }
        fs::copy(source, &target).expect("copy embedded registry asset");
        generated.push_str(&format!(
            "    ({:?}, include_bytes!(concat!(env!(\"OUT_DIR\"), \"/{relative}\"))),\n",
            relative
        ));
    }
    generated.push_str("];\n");
    fs::write(out_dir.join("embedded_registry.rs"), generated)
        .expect("write embedded registry index");
}

fn collect(root: &Path, directory: &Path, files: &mut Vec<(String, PathBuf)>) {
    let mut entries: Vec<_> = fs::read_dir(directory)
        .expect("read registry directory")
        .map(|entry| entry.expect("read registry entry").path())
        .collect();
    entries.sort();
    for path in entries {
        if path.is_dir() {
            collect(root, &path, files);
        } else if path.is_file() {
            let relative = path
                .strip_prefix(root)
                .expect("registry path")
                .to_string_lossy()
                .replace('\\', "/");
            if relative == "manifest.json"
                || relative == "schemas/broker.schema.json"
                || (relative.starts_with("brokers/")
                    && matches!(
                        Path::new(&relative).extension().and_then(|v| v.to_str()),
                        Some("yaml" | "yml")
                    )
                    && !Path::new(&relative)
                        .file_name()
                        .and_then(|v| v.to_str())
                        .is_some_and(|name| name.starts_with('_')))
            {
                files.push((relative, path));
            }
        }
    }
}
