use base64::Engine as _;
use base64::engine::general_purpose::URL_SAFE;
use sha2::{Digest, Sha256};
use symeraseme_core::storage::encryption::{
    EncryptionError, V1_HEADER, V2_HEADER, V2_SALT_LEN, V3_HEADER, V3_SALT_LEN, decrypt_v1,
    decrypt_v2, decrypt_v3,
};

// This envelope was generated by scripts/generate-crypto-fixtures.py through
// the archived python-final implementation. The plaintext is the shared DB
// fixture that the Go TestPythonFernetFixturesDecrypt test also compares.
const PYTHON_FINAL_V1: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/golden-campaign-v1-python.db");
const PYTHON_FINAL_V2: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/golden-campaign-v2-python.db");
const PYTHON_FINAL_V3: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/golden-campaign-v3-python.db");
const PYTHON_FINAL_SMALL_V3: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/small-vector-v3-python.db");
const SHARED_PLAINTEXT: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/golden-campaign.db");
const MASTER_KEY: &[u8] = b"symaira-eraseme-golden-master-32";

#[test]
fn python_final_v1_fixture_matches_shared_go_plaintext() {
    let decrypted =
        decrypt_v1(PYTHON_FINAL_V1, MASTER_KEY).expect("the Python-final V1 vector must decrypt");

    assert!(
        decrypted == SHARED_PLAINTEXT,
        "CRY-001 plaintext differs from the shared Go/Python fixture"
    );
}

#[test]
fn v1_rejects_tampering_before_decryption() {
    let mut tampered = PYTHON_FINAL_V1.to_vec();
    let token_start = V1_HEADER.len();
    tampered[token_start + 1] = if tampered[token_start + 1] == b'B' {
        b'C'
    } else {
        b'B'
    };

    assert!(matches!(
        decrypt_v1(&tampered, MASTER_KEY),
        Err(EncryptionError::AuthenticationFailed)
    ));
}

#[test]
fn v1_rejects_truncated_wrong_key_and_unsupported_inputs() {
    assert!(matches!(
        decrypt_v1(&PYTHON_FINAL_V1[..V1_HEADER.len()], MASTER_KEY),
        Err(EncryptionError::TruncatedToken)
    ));

    let mut truncated = PYTHON_FINAL_V1.to_vec();
    truncated.pop();
    assert!(decrypt_v1(&truncated, MASTER_KEY).is_err());

    let wrong_master_key = [0_u8; 32];
    assert!(matches!(
        decrypt_v1(PYTHON_FINAL_V1, &wrong_master_key),
        Err(EncryptionError::AuthenticationFailed)
    ));

    let mut unsupported = PYTHON_FINAL_V1.to_vec();
    unsupported[..V1_HEADER.len()].copy_from_slice(b"SYMERASEME_ENCv2\n");
    assert!(matches!(
        decrypt_v1(&unsupported, MASTER_KEY),
        Err(EncryptionError::UnsupportedEnvelope)
    ));

    let short_master_key = [0_u8; 31];
    assert!(matches!(
        decrypt_v1(PYTHON_FINAL_V1, &short_master_key),
        Err(EncryptionError::InvalidMasterKeyLength { actual: 31 })
    ));
}

#[test]
fn python_final_v2_fixture_matches_shared_go_plaintext() {
    assert_eq!(V2_HEADER.len(), 17);
    assert!(PYTHON_FINAL_V2.len() >= V2_HEADER.len() + V2_SALT_LEN);
    assert_eq!(&PYTHON_FINAL_V2[..V2_HEADER.len()], V2_HEADER);

    let decrypted =
        decrypt_v2(PYTHON_FINAL_V2, MASTER_KEY).expect("the Python-final V2 vector must decrypt");

    assert!(
        decrypted == SHARED_PLAINTEXT,
        "CRY-002 plaintext differs from the shared Go/Python fixture"
    );
}

#[test]
fn v2_rejects_malformed_header_and_salt_truncation() {
    let mut malformed_header = PYTHON_FINAL_V2.to_vec();
    malformed_header[..V2_HEADER.len()].copy_from_slice(V1_HEADER);
    assert!(matches!(
        decrypt_v2(&malformed_header, MASTER_KEY),
        Err(EncryptionError::UnsupportedEnvelope)
    ));

    assert!(matches!(
        decrypt_v2(&PYTHON_FINAL_V2[..V2_HEADER.len()], MASTER_KEY),
        Err(EncryptionError::TruncatedSalt)
    ));

    let truncated_salt = &PYTHON_FINAL_V2[..V2_HEADER.len() + V2_SALT_LEN - 1];
    assert!(matches!(
        decrypt_v2(truncated_salt, MASTER_KEY),
        Err(EncryptionError::TruncatedSalt)
    ));

    let token_start = V2_HEADER.len() + V2_SALT_LEN;
    assert!(matches!(
        decrypt_v2(&PYTHON_FINAL_V2[..token_start], MASTER_KEY),
        Err(EncryptionError::TruncatedToken)
    ));
}

#[test]
fn v2_rejects_wrong_master_key_and_tampered_token() {
    let wrong_master_key = [0_u8; 32];
    assert!(matches!(
        decrypt_v2(PYTHON_FINAL_V2, &wrong_master_key),
        Err(EncryptionError::AuthenticationFailed)
    ));

    let mut tampered = PYTHON_FINAL_V2.to_vec();
    let token_start = V2_HEADER.len() + V2_SALT_LEN;
    let tamper_at = token_start + 10;
    tampered[tamper_at] = if tampered[tamper_at] == b'A' {
        b'B'
    } else {
        b'A'
    };
    assert!(matches!(
        decrypt_v2(&tampered, MASTER_KEY),
        Err(EncryptionError::AuthenticationFailed)
    ));
}

#[test]
fn v2_rejects_invalid_and_unsupported_fernet_tokens() {
    let token_start = V2_HEADER.len() + V2_SALT_LEN;
    let mut invalid_base64 = PYTHON_FINAL_V2[..token_start].to_vec();
    invalid_base64.push(b'%');
    assert!(matches!(
        decrypt_v2(&invalid_base64, MASTER_KEY),
        Err(EncryptionError::InvalidBase64)
    ));

    let mut frame = URL_SAFE
        .decode(&PYTHON_FINAL_V2[token_start..])
        .expect("the committed V2 token must be decodable");
    frame[0] = 0x81;
    let unsupported_token = URL_SAFE.encode(frame);
    let mut unsupported_version = PYTHON_FINAL_V2[..token_start].to_vec();
    unsupported_version.extend_from_slice(unsupported_token.as_bytes());
    assert!(matches!(
        decrypt_v2(&unsupported_version, MASTER_KEY),
        Err(EncryptionError::UnsupportedFernetVersion(0x81))
    ));

    let short_master_key = [0_u8; 31];
    assert!(matches!(
        decrypt_v2(PYTHON_FINAL_V2, &short_master_key),
        Err(EncryptionError::InvalidMasterKeyLength { actual: 31 })
    ));
}

#[test]
fn python_final_v3_fixture_matches_shared_go_plaintext() {
    assert_eq!(V3_HEADER.len(), 17);
    assert!(PYTHON_FINAL_V3.len() >= V3_HEADER.len() + V3_SALT_LEN);
    assert_eq!(&PYTHON_FINAL_V3[..V3_HEADER.len()], V3_HEADER);

    let decrypted =
        decrypt_v3(PYTHON_FINAL_V3, MASTER_KEY).expect("the Python-final V3 vector must decrypt");
    assert_eq!(decrypted, SHARED_PLAINTEXT);

    let small = decrypt_v3(PYTHON_FINAL_SMALL_V3, MASTER_KEY)
        .expect("the small Python-final V3 vector must decrypt");
    assert_eq!(
        small,
        b"SQLite format 3\0deterministic test payload for small vector verification."
    );
}

#[test]
fn v3_rejects_malformed_header_salt_token_and_key() {
    let mut malformed_header = PYTHON_FINAL_V3.to_vec();
    malformed_header[..V3_HEADER.len()].copy_from_slice(V2_HEADER);
    assert!(matches!(
        decrypt_v3(&malformed_header, MASTER_KEY),
        Err(EncryptionError::UnsupportedEnvelope)
    ));

    assert!(matches!(
        decrypt_v3(&PYTHON_FINAL_V3[..V3_HEADER.len()], MASTER_KEY),
        Err(EncryptionError::TruncatedSalt)
    ));
    let token_start = V3_HEADER.len() + V3_SALT_LEN;
    assert!(matches!(
        decrypt_v3(&PYTHON_FINAL_V3[..token_start - 1], MASTER_KEY),
        Err(EncryptionError::TruncatedSalt)
    ));
    assert!(matches!(
        decrypt_v3(&PYTHON_FINAL_V3[..token_start], MASTER_KEY),
        Err(EncryptionError::TruncatedToken)
    ));

    let wrong_master_key = [0_u8; 32];
    assert!(matches!(
        decrypt_v3(PYTHON_FINAL_V3, &wrong_master_key),
        Err(EncryptionError::AuthenticationFailed)
    ));

    let short_master_key = [0_u8; 31];
    assert!(matches!(
        decrypt_v3(PYTHON_FINAL_V3, &short_master_key),
        Err(EncryptionError::InvalidMasterKeyLength { actual: 31 })
    ));
}

#[test]
fn v3_rejects_tampered_invalid_base64_and_unsupported_fernet_tokens() {
    let token_start = V3_HEADER.len() + V3_SALT_LEN;
    let mut tampered = PYTHON_FINAL_V3.to_vec();
    tampered[token_start + 10] = if tampered[token_start + 10] == b'A' {
        b'B'
    } else {
        b'A'
    };
    assert!(matches!(
        decrypt_v3(&tampered, MASTER_KEY),
        Err(EncryptionError::AuthenticationFailed)
    ));

    let mut invalid_base64 = PYTHON_FINAL_V3[..token_start].to_vec();
    invalid_base64.push(b'%');
    assert!(matches!(
        decrypt_v3(&invalid_base64, MASTER_KEY),
        Err(EncryptionError::InvalidBase64)
    ));

    let mut frame = URL_SAFE
        .decode(&PYTHON_FINAL_V3[token_start..])
        .expect("the committed V3 token must be decodable");
    frame[0] = 0x81;
    let unsupported_token = URL_SAFE.encode(frame);
    let mut unsupported_version = PYTHON_FINAL_V3[..token_start].to_vec();
    unsupported_version.extend_from_slice(unsupported_token.as_bytes());
    assert!(matches!(
        decrypt_v3(&unsupported_version, MASTER_KEY),
        Err(EncryptionError::UnsupportedFernetVersion(0x81))
    ));
}

#[test]
fn python_final_v3_fixture_matches_oracle_provenance() {
    let provenance: serde_json::Value = serde_json::from_slice(include_bytes!(
        "../../../tests/fixtures/event-store/crypto/provenance.json"
    ))
    .expect("the committed crypto provenance must be valid JSON");
    let expected = provenance["fixtures"]["golden-campaign-v3-python.db"]["sha256"]
        .as_str()
        .expect("the V3 oracle fixture must have a SHA-256 provenance record");
    let actual = Sha256::digest(PYTHON_FINAL_V3);
    assert_eq!(format!("{actual:x}"), expected);
}
