use symeraseme_core::storage::encryption::{EncryptionError, V1_HEADER, decrypt_v1};

// This envelope was generated by scripts/generate-crypto-fixtures.py through
// the archived python-final implementation. The plaintext is the shared DB
// fixture that the Go TestPythonFernetFixturesDecrypt test also compares.
const PYTHON_FINAL_V1: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/golden-campaign-v1-python.db");
const SHARED_PLAINTEXT: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/golden-campaign.db");
const MASTER_KEY: &[u8] = b"symaira-eraseme-golden-master-32";

#[test]
fn python_final_v1_fixture_matches_shared_go_plaintext() {
    let decrypted =
        decrypt_v1(PYTHON_FINAL_V1, MASTER_KEY).expect("the Python-final V1 vector must decrypt");

    assert!(
        decrypted == SHARED_PLAINTEXT,
        "CRY-001 plaintext differs from the shared Go/Python fixture"
    );
}

#[test]
fn v1_rejects_tampering_before_decryption() {
    let mut tampered = PYTHON_FINAL_V1.to_vec();
    let token_start = V1_HEADER.len();
    tampered[token_start + 1] = if tampered[token_start + 1] == b'B' {
        b'C'
    } else {
        b'B'
    };

    assert!(matches!(
        decrypt_v1(&tampered, MASTER_KEY),
        Err(EncryptionError::AuthenticationFailed)
    ));
}

#[test]
fn v1_rejects_truncated_wrong_key_and_unsupported_inputs() {
    assert!(matches!(
        decrypt_v1(&PYTHON_FINAL_V1[..V1_HEADER.len()], MASTER_KEY),
        Err(EncryptionError::TruncatedToken)
    ));

    let mut truncated = PYTHON_FINAL_V1.to_vec();
    truncated.pop();
    assert!(decrypt_v1(&truncated, MASTER_KEY).is_err());

    let wrong_master_key = [0_u8; 32];
    assert!(matches!(
        decrypt_v1(PYTHON_FINAL_V1, &wrong_master_key),
        Err(EncryptionError::AuthenticationFailed)
    ));

    let mut unsupported = PYTHON_FINAL_V1.to_vec();
    unsupported[..V1_HEADER.len()].copy_from_slice(b"SYMERASEME_ENCv2\n");
    assert!(matches!(
        decrypt_v1(&unsupported, MASTER_KEY),
        Err(EncryptionError::UnsupportedEnvelope)
    ));

    let short_master_key = [0_u8; 31];
    assert!(matches!(
        decrypt_v1(PYTHON_FINAL_V1, &short_master_key),
        Err(EncryptionError::InvalidMasterKeyLength { actual: 31 })
    ));
}
