use base64::Engine as _;
use base64::engine::general_purpose::URL_SAFE;
use hmac::{Hmac, KeyInit, Mac};
use pbkdf2::pbkdf2_hmac;
use sha2::{Digest, Sha256};
use std::io::Write;
use std::process::{Command, Output, Stdio};
use symeraseme_core::storage::encryption::{
    EncryptionError, PBKDF2_ITERATIONS, V1_FIXED_SALT, V1_HEADER, V2_HEADER, V2_SALT_LEN,
    V3_HEADER, V3_HKDF_INFO, V3_SALT_LEN, decrypt_v1, decrypt_v2, decrypt_v3,
};
use zeroize::Zeroize;

// This envelope was generated by scripts/generate-crypto-fixtures.py through
// the archived python-final implementation. The plaintext is the shared DB
// fixture that the Go TestPythonFernetFixturesDecrypt test also compares.
const PYTHON_FINAL_V1: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/golden-campaign-v1-python.db");
const PYTHON_FINAL_V2: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/golden-campaign-v2-python.db");
const PYTHON_FINAL_V3: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/golden-campaign-v3-python.db");
const PYTHON_FINAL_SMALL_V3: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/small-vector-v3-python.db");
const LEGACY_GO_V1: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/golden-campaign-v1-legacy-go.db");
const LEGACY_GO_V2: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/golden-campaign-v2-legacy-go.db");
const LEGACY_GO_V3: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/golden-campaign-v3-legacy-go.db");
const LEGACY_GO_SMALL_V3: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/small-vector-v3-legacy-go.db");
const SHARED_PLAINTEXT: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/golden-campaign.db");
const MASTER_KEY: &[u8] = b"symaira-eraseme-golden-master-32";
const WRONG_MASTER_KEY: &[u8] = b"incorrect-master-key-fixture-000";
const SMALL_PLAINTEXT: &[u8] =
    b"SQLite format 3\0deterministic test payload for small vector verification.";
const LEGACY_GO_MIN_TOKEN_LEN: usize = 69;
const LEGACY_GO_OUTER_HMAC_LEN: usize = 32;
const CRYPTO_PROVENANCE: &[u8] =
    include_bytes!("../../../tests/fixtures/event-store/crypto/provenance.json");

type HmacSha256 = Hmac<Sha256>;
type DecryptEnvelope = fn(&[u8], &[u8]) -> Result<Vec<u8>, EncryptionError>;

#[derive(Clone, Copy, Debug)]
enum LegacyEnvelopeVersion {
    V1,
    V2,
    V3,
}

impl LegacyEnvelopeVersion {
    fn token_start(self) -> usize {
        match self {
            Self::V1 => V1_HEADER.len(),
            Self::V2 => V2_HEADER.len() + V2_SALT_LEN,
            Self::V3 => V3_HEADER.len() + V3_SALT_LEN,
        }
    }

    fn derive_key(self, envelope: &[u8], master_key: &[u8]) -> [u8; 32] {
        let mut key = [0_u8; 32];
        match self {
            Self::V1 => {
                pbkdf2_hmac::<Sha256>(master_key, V1_FIXED_SALT, PBKDF2_ITERATIONS, &mut key);
            }
            Self::V2 => {
                pbkdf2_hmac::<Sha256>(
                    master_key,
                    &envelope[V2_HEADER.len()..self.token_start()],
                    PBKDF2_ITERATIONS,
                    &mut key,
                );
            }
            Self::V3 => {
                let salt = &envelope[V3_HEADER.len()..self.token_start()];
                key = derive_v3_legacy_key(master_key, salt);
            }
        }
        key
    }
}

struct LegacyMutation {
    id: &'static str,
    envelope: Vec<u8>,
    master_key: &'static [u8],
}

fn derive_v3_legacy_key(master_key: &[u8], salt: &[u8]) -> [u8; 32] {
    let mut extract =
        <HmacSha256 as KeyInit>::new_from_slice(salt).expect("HMAC accepts the fixed salt");
    extract.update(master_key);
    let mut pseudorandom_key = extract.finalize().into_bytes();
    let mut expand = <HmacSha256 as KeyInit>::new_from_slice(&pseudorandom_key)
        .expect("HMAC accepts the fixed PRK");
    expand.update(V3_HKDF_INFO);
    expand.update(&[1]);
    let block = expand.finalize().into_bytes();
    let mut key = [0_u8; 32];
    key.copy_from_slice(&block);
    pseudorandom_key.zeroize();
    key
}

fn legacy_mutation_cases(version: LegacyEnvelopeVersion, fixture: &[u8]) -> Vec<LegacyMutation> {
    let token_start = version.token_start();
    assert!(fixture.len() >= token_start + LEGACY_GO_MIN_TOKEN_LEN);

    let mut bad_header = fixture.to_vec();
    bad_header[0] ^= 0x01;

    let truncated_raw_token = fixture[..token_start + LEGACY_GO_MIN_TOKEN_LEN - 1].to_vec();

    let mut outer_hmac_tampered = fixture.to_vec();
    *outer_hmac_tampered
        .last_mut()
        .expect("legacy fixture includes an outer HMAC") ^= 0x01;

    let mut raw_version_invalid = fixture.to_vec();
    raw_version_invalid[token_start] = 0x81;

    let mut gcm_tag_tampered_rehmaced = fixture.to_vec();
    let mac_offset = gcm_tag_tampered_rehmaced.len() - LEGACY_GO_OUTER_HMAC_LEN;
    gcm_tag_tampered_rehmaced[mac_offset - 1] ^= 0x01;
    let mut derived_key = version.derive_key(&gcm_tag_tampered_rehmaced, MASTER_KEY);
    let mut mac = <HmacSha256 as KeyInit>::new_from_slice(&derived_key)
        .expect("HMAC accepts the derived key");
    mac.update(&gcm_tag_tampered_rehmaced[..mac_offset]);
    gcm_tag_tampered_rehmaced[mac_offset..].copy_from_slice(&mac.finalize().into_bytes());
    derived_key.zeroize();

    vec![
        LegacyMutation {
            id: "bad_header",
            envelope: bad_header,
            master_key: MASTER_KEY,
        },
        LegacyMutation {
            id: "truncated_raw_token",
            envelope: truncated_raw_token,
            master_key: MASTER_KEY,
        },
        LegacyMutation {
            id: "wrong_master_key",
            envelope: fixture.to_vec(),
            master_key: WRONG_MASTER_KEY,
        },
        LegacyMutation {
            id: "outer_hmac_tampered",
            envelope: outer_hmac_tampered,
            master_key: MASTER_KEY,
        },
        LegacyMutation {
            id: "raw_version_invalid",
            envelope: raw_version_invalid,
            master_key: MASTER_KEY,
        },
        LegacyMutation {
            id: "gcm_tag_tampered_rehmaced",
            envelope: gcm_tag_tampered_rehmaced,
            master_key: MASTER_KEY,
        },
    ]
}

fn assert_fails_closed(case_id: &str, result: Result<Vec<u8>, EncryptionError>) {
    match result {
        Ok(_) => panic!("{case_id}: invalid legacy token yielded plaintext"),
        Err(error) => {
            let rendered = format!("{error}\n{error:?}");
            for marker in [
                "symaira-eraseme-golden-master-32",
                "incorrect-master-key-fixture-000",
                "SQLite format 3",
                "deterministic test payload",
            ] {
                assert!(
                    !rendered.contains(marker),
                    "{case_id}: error leaked protected material"
                );
            }
        }
    }
}

fn assert_fixture_matches_provenance(name: &str, fixture: &[u8]) {
    let provenance: serde_json::Value = serde_json::from_slice(CRYPTO_PROVENANCE)
        .expect("the committed crypto provenance is valid");
    let record = &provenance["fixtures"][name];
    let expected_hash = record["sha256"]
        .as_str()
        .expect("the fixture has a SHA-256 provenance record");
    let expected_size = record["size"]
        .as_u64()
        .expect("the fixture has a size provenance record");
    assert_eq!(
        hex::encode(Sha256::digest(fixture)),
        expected_hash,
        "{name}"
    );
    assert_eq!(fixture.len() as u64, expected_size, "{name}");
}

fn run_go_crypto_oracle(operation: u8, key: &[u8], payload: &[u8]) -> Output {
    let oracle = std::path::Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../rust-tests/parity/oracle/crypto");
    let mut child = Command::new("go")
        .args(["run", "."])
        .current_dir(oracle)
        .stdin(Stdio::piped())
        .stdout(Stdio::piped())
        .stderr(Stdio::piped())
        .spawn()
        .expect("Go crypto oracle must start");
    let mut request = Vec::with_capacity(1 + key.len() + payload.len());
    request.push(operation);
    request.extend_from_slice(key);
    request.extend_from_slice(payload);
    child
        .stdin
        .take()
        .expect("Go oracle stdin is available")
        .write_all(&request)
        .expect("Go oracle request writes");
    child.wait_with_output().expect("Go oracle must finish")
}

fn assert_go_crypto_oracle_success(key: &[u8], envelope: &[u8], expected: &[u8]) {
    let output = run_go_crypto_oracle(b'd', key, envelope);
    assert!(
        output.status.success(),
        "Go crypto oracle rejected a valid legacy envelope: {:?}",
        output.stderr
    );
    assert!(output.stderr.is_empty(), "Go crypto oracle emitted stderr");
    assert_eq!(output.stdout, expected);
}

fn assert_go_crypto_oracle_rejects(case_id: &str, key: &[u8], envelope: &[u8]) {
    let output = run_go_crypto_oracle(b'd', key, envelope);
    assert!(
        !output.status.success(),
        "{case_id}: Go crypto oracle accepted an invalid envelope"
    );
    assert!(output.stdout.is_empty(), "{case_id}: Go emitted plaintext");
    assert!(
        output.stderr.starts_with(b"crypto operation failed\n"),
        "{case_id}: unexpected Go oracle stderr: {:?}",
        output.stderr
    );
}

#[test]
fn python_final_v1_fixture_matches_shared_go_plaintext() {
    let decrypted =
        decrypt_v1(PYTHON_FINAL_V1, MASTER_KEY).expect("the Python-final V1 vector must decrypt");

    assert!(
        decrypted == SHARED_PLAINTEXT,
        "CRY-001 plaintext differs from the shared Go/Python fixture"
    );
}

#[test]
fn v1_rejects_tampering_before_decryption() {
    let mut tampered = PYTHON_FINAL_V1.to_vec();
    let token_start = V1_HEADER.len();
    tampered[token_start + 1] = if tampered[token_start + 1] == b'B' {
        b'C'
    } else {
        b'B'
    };

    assert!(matches!(
        decrypt_v1(&tampered, MASTER_KEY),
        Err(EncryptionError::AuthenticationFailed)
    ));
}

#[test]
fn v1_rejects_truncated_wrong_key_and_unsupported_inputs() {
    assert!(matches!(
        decrypt_v1(&PYTHON_FINAL_V1[..V1_HEADER.len()], MASTER_KEY),
        Err(EncryptionError::TruncatedToken)
    ));

    let mut truncated = PYTHON_FINAL_V1.to_vec();
    truncated.pop();
    assert!(decrypt_v1(&truncated, MASTER_KEY).is_err());

    let wrong_master_key = [0_u8; 32];
    assert!(matches!(
        decrypt_v1(PYTHON_FINAL_V1, &wrong_master_key),
        Err(EncryptionError::AuthenticationFailed)
    ));

    let mut unsupported = PYTHON_FINAL_V1.to_vec();
    unsupported[..V1_HEADER.len()].copy_from_slice(b"SYMERASEME_ENCv2\n");
    assert!(matches!(
        decrypt_v1(&unsupported, MASTER_KEY),
        Err(EncryptionError::UnsupportedEnvelope)
    ));

    let short_master_key = [0_u8; 31];
    assert!(matches!(
        decrypt_v1(PYTHON_FINAL_V1, &short_master_key),
        Err(EncryptionError::InvalidMasterKeyLength { actual: 31 })
    ));
}

#[test]
fn python_final_v2_fixture_matches_shared_go_plaintext() {
    assert_eq!(V2_HEADER.len(), 17);
    assert!(PYTHON_FINAL_V2.len() >= V2_HEADER.len() + V2_SALT_LEN);
    assert_eq!(&PYTHON_FINAL_V2[..V2_HEADER.len()], V2_HEADER);

    let decrypted =
        decrypt_v2(PYTHON_FINAL_V2, MASTER_KEY).expect("the Python-final V2 vector must decrypt");

    assert!(
        decrypted == SHARED_PLAINTEXT,
        "CRY-002 plaintext differs from the shared Go/Python fixture"
    );
}

#[test]
fn v2_rejects_malformed_header_and_salt_truncation() {
    let mut malformed_header = PYTHON_FINAL_V2.to_vec();
    malformed_header[..V2_HEADER.len()].copy_from_slice(V1_HEADER);
    assert!(matches!(
        decrypt_v2(&malformed_header, MASTER_KEY),
        Err(EncryptionError::UnsupportedEnvelope)
    ));

    assert!(matches!(
        decrypt_v2(&PYTHON_FINAL_V2[..V2_HEADER.len()], MASTER_KEY),
        Err(EncryptionError::TruncatedSalt)
    ));

    let truncated_salt = &PYTHON_FINAL_V2[..V2_HEADER.len() + V2_SALT_LEN - 1];
    assert!(matches!(
        decrypt_v2(truncated_salt, MASTER_KEY),
        Err(EncryptionError::TruncatedSalt)
    ));

    let token_start = V2_HEADER.len() + V2_SALT_LEN;
    assert!(matches!(
        decrypt_v2(&PYTHON_FINAL_V2[..token_start], MASTER_KEY),
        Err(EncryptionError::TruncatedToken)
    ));
}

#[test]
fn v2_rejects_wrong_master_key_and_tampered_token() {
    let wrong_master_key = [0_u8; 32];
    assert!(matches!(
        decrypt_v2(PYTHON_FINAL_V2, &wrong_master_key),
        Err(EncryptionError::AuthenticationFailed)
    ));

    let mut tampered = PYTHON_FINAL_V2.to_vec();
    let token_start = V2_HEADER.len() + V2_SALT_LEN;
    let tamper_at = token_start + 10;
    tampered[tamper_at] = if tampered[tamper_at] == b'A' {
        b'B'
    } else {
        b'A'
    };
    assert!(matches!(
        decrypt_v2(&tampered, MASTER_KEY),
        Err(EncryptionError::AuthenticationFailed)
    ));
}

#[test]
fn v2_rejects_invalid_and_unsupported_fernet_tokens() {
    let token_start = V2_HEADER.len() + V2_SALT_LEN;
    let mut invalid_base64 = PYTHON_FINAL_V2[..token_start].to_vec();
    invalid_base64.push(b'%');
    assert!(matches!(
        decrypt_v2(&invalid_base64, MASTER_KEY),
        Err(EncryptionError::InvalidBase64)
    ));

    let mut frame = URL_SAFE
        .decode(&PYTHON_FINAL_V2[token_start..])
        .expect("the committed V2 token must be decodable");
    frame[0] = 0x81;
    let unsupported_token = URL_SAFE.encode(frame);
    let mut unsupported_version = PYTHON_FINAL_V2[..token_start].to_vec();
    unsupported_version.extend_from_slice(unsupported_token.as_bytes());
    assert!(matches!(
        decrypt_v2(&unsupported_version, MASTER_KEY),
        Err(EncryptionError::UnsupportedFernetVersion(0x81))
    ));

    let short_master_key = [0_u8; 31];
    assert!(matches!(
        decrypt_v2(PYTHON_FINAL_V2, &short_master_key),
        Err(EncryptionError::InvalidMasterKeyLength { actual: 31 })
    ));
}

#[test]
fn python_final_v3_fixture_matches_shared_go_plaintext() {
    assert_eq!(V3_HEADER.len(), 17);
    assert!(PYTHON_FINAL_V3.len() >= V3_HEADER.len() + V3_SALT_LEN);
    assert_eq!(&PYTHON_FINAL_V3[..V3_HEADER.len()], V3_HEADER);

    let decrypted =
        decrypt_v3(PYTHON_FINAL_V3, MASTER_KEY).expect("the Python-final V3 vector must decrypt");
    assert_eq!(decrypted, SHARED_PLAINTEXT);

    let small = decrypt_v3(PYTHON_FINAL_SMALL_V3, MASTER_KEY)
        .expect("the small Python-final V3 vector must decrypt");
    assert_eq!(
        small,
        b"SQLite format 3\0deterministic test payload for small vector verification."
    );
}

#[test]
fn v3_rejects_malformed_header_salt_token_and_key() {
    let mut malformed_header = PYTHON_FINAL_V3.to_vec();
    malformed_header[..V3_HEADER.len()].copy_from_slice(V2_HEADER);
    assert!(matches!(
        decrypt_v3(&malformed_header, MASTER_KEY),
        Err(EncryptionError::UnsupportedEnvelope)
    ));

    assert!(matches!(
        decrypt_v3(&PYTHON_FINAL_V3[..V3_HEADER.len()], MASTER_KEY),
        Err(EncryptionError::TruncatedSalt)
    ));
    let token_start = V3_HEADER.len() + V3_SALT_LEN;
    assert!(matches!(
        decrypt_v3(&PYTHON_FINAL_V3[..token_start - 1], MASTER_KEY),
        Err(EncryptionError::TruncatedSalt)
    ));
    assert!(matches!(
        decrypt_v3(&PYTHON_FINAL_V3[..token_start], MASTER_KEY),
        Err(EncryptionError::TruncatedToken)
    ));

    let wrong_master_key = [0_u8; 32];
    assert!(matches!(
        decrypt_v3(PYTHON_FINAL_V3, &wrong_master_key),
        Err(EncryptionError::AuthenticationFailed)
    ));

    let short_master_key = [0_u8; 31];
    assert!(matches!(
        decrypt_v3(PYTHON_FINAL_V3, &short_master_key),
        Err(EncryptionError::InvalidMasterKeyLength { actual: 31 })
    ));
}

#[test]
fn v3_rejects_tampered_invalid_base64_and_unsupported_fernet_tokens() {
    let token_start = V3_HEADER.len() + V3_SALT_LEN;
    let mut tampered = PYTHON_FINAL_V3.to_vec();
    tampered[token_start + 10] = if tampered[token_start + 10] == b'A' {
        b'B'
    } else {
        b'A'
    };
    assert!(matches!(
        decrypt_v3(&tampered, MASTER_KEY),
        Err(EncryptionError::AuthenticationFailed)
    ));

    let mut invalid_base64 = PYTHON_FINAL_V3[..token_start].to_vec();
    invalid_base64.push(b'%');
    assert!(matches!(
        decrypt_v3(&invalid_base64, MASTER_KEY),
        Err(EncryptionError::InvalidBase64)
    ));

    let mut frame = URL_SAFE
        .decode(&PYTHON_FINAL_V3[token_start..])
        .expect("the committed V3 token must be decodable");
    frame[0] = 0x81;
    let unsupported_token = URL_SAFE.encode(frame);
    let mut unsupported_version = PYTHON_FINAL_V3[..token_start].to_vec();
    unsupported_version.extend_from_slice(unsupported_token.as_bytes());
    assert!(matches!(
        decrypt_v3(&unsupported_version, MASTER_KEY),
        Err(EncryptionError::UnsupportedFernetVersion(0x81))
    ));
}

#[test]
fn legacy_go_v1_v2_fixtures_match_shared_go_plaintext() {
    let cases: [(&str, LegacyEnvelopeVersion, &[u8], DecryptEnvelope); 2] = [
        (
            "golden-campaign-v1-legacy-go.db",
            LegacyEnvelopeVersion::V1,
            LEGACY_GO_V1,
            decrypt_v1,
        ),
        (
            "golden-campaign-v2-legacy-go.db",
            LegacyEnvelopeVersion::V2,
            LEGACY_GO_V2,
            decrypt_v2,
        ),
    ];
    assert_eq!(cases.len(), 2, "CRY-006 V1/V2 fixture cardinality");

    for (name, version, fixture, decrypt) in cases {
        assert_fixture_matches_provenance(name, fixture);
        assert_eq!(
            decrypt(fixture, MASTER_KEY).expect("legacy Go fixture must decrypt"),
            SHARED_PLAINTEXT,
            "{name} ({version:?})"
        );
        assert_go_crypto_oracle_success(MASTER_KEY, fixture, SHARED_PLAINTEXT);
    }
}

#[test]
fn legacy_go_v3_full_and_small_fixtures_match_go_oracle_and_shared_plaintext() {
    let cases = [
        (
            "golden-campaign-v3-legacy-go.db",
            LEGACY_GO_V3,
            SHARED_PLAINTEXT,
        ),
        (
            "small-vector-v3-legacy-go.db",
            LEGACY_GO_SMALL_V3,
            SMALL_PLAINTEXT,
        ),
    ];
    assert_eq!(cases.len(), 2, "CRY-006 V3 fixture cardinality");

    for (name, fixture, expected_plaintext) in cases {
        assert_fixture_matches_provenance(name, fixture);
        assert_eq!(
            decrypt_v3(fixture, MASTER_KEY).expect("legacy Go V3 fixture must decrypt"),
            expected_plaintext,
            "{name}"
        );
        assert_go_crypto_oracle_success(MASTER_KEY, fixture, expected_plaintext);
    }
}

#[test]
fn legacy_go_v1_v2_mutation_corpus_fails_closed_without_leaks() {
    let cases: [(LegacyEnvelopeVersion, &[u8], DecryptEnvelope); 2] = [
        (LegacyEnvelopeVersion::V1, LEGACY_GO_V1, decrypt_v1),
        (LegacyEnvelopeVersion::V2, LEGACY_GO_V2, decrypt_v2),
    ];
    let mut case_count = 0;

    for (version, fixture, decrypt) in cases {
        let mutations = legacy_mutation_cases(version, fixture);
        assert_eq!(
            mutations.len(),
            6,
            "CRY-006 per-version mutation cardinality"
        );
        for mutation in mutations {
            case_count += 1;
            assert_fails_closed(
                mutation.id,
                decrypt(&mutation.envelope, mutation.master_key),
            );
            assert_go_crypto_oracle_rejects(mutation.id, mutation.master_key, &mutation.envelope);
        }
    }

    assert_eq!(case_count, 12, "CRY-006 V1/V2 mutation cardinality");
}

#[test]
fn legacy_go_v3_mutation_corpus_matches_go_oracle_and_fails_closed_without_leaks() {
    let mutations = legacy_mutation_cases(LegacyEnvelopeVersion::V3, LEGACY_GO_V3);
    assert_eq!(mutations.len(), 6, "CRY-006 V3 mutation cardinality");
    let mut go_comparison_count = 0;

    for mutation in mutations {
        assert_fails_closed(
            mutation.id,
            decrypt_v3(&mutation.envelope, mutation.master_key),
        );

        assert_go_crypto_oracle_rejects(mutation.id, mutation.master_key, &mutation.envelope);
        go_comparison_count += 1;
    }

    assert_eq!(
        go_comparison_count, 6,
        "CRY-006 V3 Go-oracle failure cardinality"
    );
}

#[test]
fn python_final_v3_fixture_matches_oracle_provenance() {
    let provenance: serde_json::Value = serde_json::from_slice(include_bytes!(
        "../../../tests/fixtures/event-store/crypto/provenance.json"
    ))
    .expect("the committed crypto provenance must be valid JSON");
    let expected = provenance["fixtures"]["golden-campaign-v3-python.db"]["sha256"]
        .as_str()
        .expect("the V3 oracle fixture must have a SHA-256 provenance record");
    let actual = Sha256::digest(PYTHON_FINAL_V3);
    assert_eq!(hex::encode(actual), expected);
}

#[test]
fn rust_writer_is_consumed_by_go_oracle_and_go_writer_by_rust() {
    let key = [0x41_u8; 32];
    let plaintext = b"SQLite format 3\0binary\xff payload at a block boundary";

    let rust_envelope = symeraseme_core::storage::encryption::encrypt_v3(plaintext, &key)
        .expect("Rust V3 writer must succeed");
    assert_go_crypto_oracle_success(&key, &rust_envelope, plaintext);

    let go_output = run_go_crypto_oracle(b'e', &key, plaintext);
    assert!(
        go_output.status.success(),
        "Go oracle failed: {:?}",
        go_output.stderr
    );
    assert!(go_output.stderr.is_empty(), "Go oracle emitted stderr");
    let go_envelope = go_output.stdout;
    assert_eq!(decrypt_v3(&go_envelope, &key).unwrap(), plaintext);
}
