//! DOM-004 corpus replay: the shared broker-reply corpus, as Go bytes.
//!
//! `tests/fixtures/broker_replies/*.txt` previously had no consumer at all —
//! it survived the Python-era removal as residue and was explicitly recorded in
//! the contract ledger as *not* evidence. This test turns it into evidence.
//!
//! The fixture is generated by `rust-tests/parity/oracle/triage-corpus`, which
//! runs the real `internal/triage` functions over each corpus file. Every
//! recorded prompt byte comes out of Go; nothing in the fixture was written by
//! hand, and the corpus files are inputs rather than expectations.
//!
//! Provenance follows the `dom004a`/`dom004b` discipline: the fixture asserts
//! the digest of each Go source it pins *and* the digest of each corpus file,
//! so a corpus edit invalidates the fixture instead of silently passing.

use base64::{Engine as _, engine::general_purpose::STANDARD};
use serde::Deserialize;
use sha2::{Digest, Sha256};
use std::collections::BTreeMap;
use symeraseme_core::triage_contract::select_fallback_template;
use symeraseme_core::triage_prompts::build_user_prompt;

const FIXTURE: &str = include_str!("../../../tests/fixtures/triage-corpus/dom004c.json");
const CLASSIFIER_GO: &[u8] = include_bytes!("../../../internal/triage/classifier.go");
const REBUTTAL_GO: &[u8] = include_bytes!("../../../internal/triage/rebuttal.go");
const CORPUS_ACK: &[u8] = include_bytes!("../../../tests/fixtures/broker_replies/ack_gdpr.txt");
const CORPUS_OOTO: &[u8] =
    include_bytes!("../../../tests/fixtures/broker_replies/autoresponder_ooto.txt");
const CORPUS_BOUNCE: &[u8] =
    include_bytes!("../../../tests/fixtures/broker_replies/bounce_no_mailbox.txt");
const CORPUS_DELETED: &[u8] =
    include_bytes!("../../../tests/fixtures/broker_replies/confirmed_account_deleted.txt");
const CORPUS_REJECTED: &[u8] =
    include_bytes!("../../../tests/fixtures/broker_replies/rejected_invalid_id.txt");
const CORPUS_VERIFY: &[u8] =
    include_bytes!("../../../tests/fixtures/broker_replies/verification_needed.txt");

#[derive(Debug, Deserialize)]
struct Fixture {
    schema: String,
    oracle_revision: String,
    source_sha256: BTreeMap<String, String>,
    cases: Vec<CorpusCase>,
}

#[derive(Debug, Deserialize)]
struct CorpusCase {
    name: String,
    corpus_file: String,
    corpus_sha256: String,
    broker_name: String,
    broker_website: String,
    reply_subject: String,
    reply_body: String,
    fallback_template: String,
    prompt_base64: String,
    prompt_bytes: usize,
}

fn fixture() -> Fixture {
    serde_json::from_str(FIXTURE).expect("DOM-004c fixture must be valid JSON")
}

fn sha256_hex(bytes: &[u8]) -> String {
    hex::encode(Sha256::digest(bytes))
}

fn corpus_bytes(case: &CorpusCase) -> &'static [u8] {
    match case.corpus_file.rsplit('/').next().unwrap_or_default() {
        "ack_gdpr.txt" => CORPUS_ACK,
        "autoresponder_ooto.txt" => CORPUS_OOTO,
        "bounce_no_mailbox.txt" => CORPUS_BOUNCE,
        "confirmed_account_deleted.txt" => CORPUS_DELETED,
        "rejected_invalid_id.txt" => CORPUS_REJECTED,
        "verification_needed.txt" => CORPUS_VERIFY,
        other => panic!("corpus file {other} is not pinned by this test"),
    }
}

/// The fixture must pin the Go sources it claims to, or the recorded bytes
/// describe a revision that no longer exists.
#[test]
fn fixture_pins_the_go_sources_it_was_generated_from() {
    let fixture = fixture();
    assert_eq!(fixture.schema, "symaira-eraseme.triage-corpus.v1");
    assert_eq!(
        fixture.oracle_revision.len(),
        40,
        "oracle_revision must be a full commit id, got {:?}",
        fixture.oracle_revision
    );
    assert_eq!(
        fixture.source_sha256["internal/triage/classifier.go"],
        sha256_hex(CLASSIFIER_GO)
    );
    assert_eq!(
        fixture.source_sha256["internal/triage/rebuttal.go"],
        sha256_hex(REBUTTAL_GO)
    );
}

/// Every corpus file the fixture covers must still hash to the recorded digest.
#[test]
fn every_corpus_file_matches_its_recorded_digest() {
    let fixture = fixture();
    assert_eq!(fixture.cases.len(), 6, "the corpus holds six replies");
    for case in &fixture.cases {
        assert_eq!(
            case.corpus_sha256,
            sha256_hex(corpus_bytes(case)),
            "corpus file {} changed since the fixture was generated",
            case.corpus_file
        );
    }
}

/// The replay: Rust must reproduce Go's prompt bytes for every corpus reply.
#[test]
fn rust_reproduces_go_prompt_bytes_for_every_corpus_reply() {
    let fixture = fixture();
    for case in &fixture.cases {
        let produced = build_user_prompt(
            &case.broker_name,
            &case.broker_website,
            "",
            "",
            &case.reply_subject,
            &case.reply_body,
            None,
        );
        let expected = STANDARD
            .decode(&case.prompt_base64)
            .expect("prompt_base64 decodes");
        assert_eq!(
            produced.as_ref(),
            expected.as_slice(),
            "prompt bytes diverge from Go for corpus case {}",
            case.name
        );
        assert_eq!(
            produced.as_ref().len(),
            case.prompt_bytes,
            "recorded byte count disagrees with the recorded bytes for {}",
            case.name
        );
    }
}

/// The fallback template selection must agree with Go per corpus reply. Three
/// of the six carry no matching keyword, so the empty result is part of the
/// contract rather than an omission.
#[test]
fn rust_selects_the_same_fallback_template_as_go() {
    let fixture = fixture();
    for case in &fixture.cases {
        assert_eq!(
            select_fallback_template(&case.reply_body),
            case.fallback_template,
            "fallback template diverges from Go for corpus case {}",
            case.name
        );
    }
}

/// Guards the corpus itself: the classification the corpus is meant to
/// exercise must actually be present, so a corpus that silently lost its
/// distinguishing content fails here rather than passing vacuously.
#[test]
fn corpus_still_holds_its_distinguishing_replies() {
    let fixture = fixture();
    let by_name = |name: &str| {
        fixture
            .cases
            .iter()
            .find(|case| case.name == name)
            .unwrap_or_else(|| panic!("corpus case {name} missing"))
    };
    // A bounce must look like a bounce, a rejection like a rejection, and so on.
    assert!(
        by_name("bounce_no_mailbox")
            .reply_body
            .contains("Delivery Status Notification"),
        "the bounce reply lost its delivery-failure marker"
    );
    assert!(
        by_name("verification_needed")
            .reply_body
            .contains("verify your identity"),
        "the verification reply lost its identity-challenge marker"
    );
    assert!(
        by_name("confirmed_account_deleted")
            .reply_body
            .contains("permanently deleted"),
        "the confirmation reply lost its deletion marker"
    );
    assert!(
        by_name("autoresponder_ooto")
            .reply_body
            .contains("out of the office"),
        "the autoresponder reply lost its out-of-office marker"
    );
    // The two keyword matches are what make the fallback test non-vacuous.
    assert_eq!(
        by_name("verification_needed").fallback_template,
        "identity_challenged"
    );
    assert_eq!(
        by_name("rejected_invalid_id").fallback_template,
        "address_mismatch"
    );
}
