"""Scheduler generator — platform-specific scheduler configs for lifecycle tasks.

Generates copy-paste ready cron, launchd (macOS), and systemd (Linux)
configurations for the OpenEraseMe lifecycle commands:

- **tick** (daily)       — check deadlines, send reminders, escalate
- **poll-inbox** (hourly) — poll IMAP inbox for broker replies
- **re-scan** (quarterly) — trigger re-scans for expired confirmations

Each config includes a wrapper script that activates the virtualenv and
runs the proper command.
"""

from __future__ import annotations

import logging
import os
import platform
import stat
from dataclasses import dataclass, field
from datetime import datetime, time
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Data
# ---------------------------------------------------------------------------

TICK_DEFAULT_TIME = time(10, 0)  # 10:00 daily
POLL_TIMES = [time(8, 0), time(12, 0), time(16, 0), time(20, 0)]  # 4x daily
RESCAN_INTERVAL_MONTHS = 3  # quarterly


@dataclass
class SchedulerConfig:
    """Combined schedule specification."""

    tick_time: time = TICK_DEFAULT_TIME
    poll_times: list[time] = field(default_factory=lambda: list(POLL_TIMES))
    rescan_interval_months: int = RESCAN_INTERVAL_MONTHS
    openeraseme_bin: str = ""
    venv_activate: str = ""
    output_dir: str = "./schedules"
    platform: str = ""


def detect_platform() -> str:
    """Detect the native scheduling platform."""
    system = platform.system().lower()
    if system == "darwin":
        return "launchd"
    if system == "linux":
        # Check for systemd
        try:
            import subprocess

            result = subprocess.run(
                ["systemctl", "--version"],
                capture_output=True,
                text=True,
                timeout=5,
            )
            if result.returncode == 0:
                return "systemd"
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass
        return "cron"
    return "cron"


def _resolve_bin() -> str:
    """Resolve the openeraseme binary path."""
    from shutil import which

    return which("openeraseme") or os.environ.get(
        "OPENERASEME_BIN", "/usr/local/bin/openeraseme"
    )


def _resolve_venv() -> str:
    """Resolve the virtualenv activate path."""
    import sys

    if sys.prefix != sys.base_prefix:
        activate = Path(sys.prefix) / "bin" / "activate"
        if activate.exists():
            return str(activate)
    return os.environ.get("OPENERASEME_VENV", "")


# ---------------------------------------------------------------------------
# Wrapper script
# ---------------------------------------------------------------------------

WRAPPER_HEADER = """#!/usr/bin/env bash
# OpenEraseMe scheduled task wrapper
# Generated by openeraseme generate-scheduler
set -euo pipefail

{venv_block}

export OPENERASEME_HEADLESS=1
export PATH="${{PATH}}:/usr/local/bin:/opt/homebrew/bin"

cd "{project_dir}"

{command}
"""


def _wrapper_script(
    command: str,
    project_dir: str = "",
    venv_activate: str = "",
) -> str:
    """Generate a shell wrapper script for a scheduler command."""
    if not project_dir:
        project_dir = str(Path.cwd())
    if not venv_activate:
        venv_activate = _resolve_venv()

    venv_block = f'source "{venv_activate}"' if venv_activate else ""

    return WRAPPER_HEADER.format(
        venv_block=venv_block,
        project_dir=project_dir,
        command=command,
    )


# ---------------------------------------------------------------------------
# Cron generator
# ---------------------------------------------------------------------------


def generate_cron(
    config: SchedulerConfig,
    project_dir: str = "",
) -> dict[str, str]:
    """Generate cron tab entries and wrapper scripts.

    Returns a dict mapping filename -> content.
    """
    bin_path = config.openeraseme_bin or _resolve_bin()
    venv = config.venv_activate or _resolve_venv()
    out: dict[str, str] = {}

    # ── tick (daily) ──
    tick_cmd = f"{bin_path} tick --output json"
    out["openeraseme-tick.sh"] = _wrapper_script(
        tick_cmd, project_dir=project_dir, venv_activate=venv
    )

    # ── poll-inbox (hourly via wrapper with time check) ──
    # Since cron doesn't handle multiple daily times well, we check in the wrapper
    poll_times_str = "|".join(f"{t.hour:02d}:{t.minute:02d}" for t in config.poll_times)
    poll_wrapper = f"""#!/usr/bin/env bash
set -euo pipefail

{('source "' + venv + '"') if venv else ''}
export OPENERASEME_HEADLESS=1
export PATH="${{PATH}}:/usr/local/bin:/opt/homebrew/bin"
cd "{project_dir}"

# Only run at configured poll times
CURRENT_HHMM=$(date +%H:%M)
case "$CURRENT_HHMM" in
{poll_times_str})
    {bin_path} poll-inbox --output json
    ;;
esac
"""
    out["openeraseme-poll.sh"] = poll_wrapper

    # ── re-scan (quarterly) ──
    rescan_cmd = f"{bin_path} tick --output json --dry-run"
    # Re-scan runs quarterly (every 3 months)
    out["openeraseme-rescan.sh"] = _wrapper_script(
        rescan_cmd, project_dir=project_dir, venv_activate=venv
    )

    # ── Crontab entries ──
    crontab_lines = [
        "# OpenEraseMe scheduled tasks",
        f"# Generated by openeraseme generate-scheduler on {datetime.now().isoformat()}",
        "",
        f"# Tick (daily at {config.tick_time.hour:02d}:{config.tick_time.minute:02d})",
        "{} {} * * * {}/openeraseme-tick.sh".format(
            config.tick_time.minute,
            config.tick_time.hour,
            "{wrapper_dir}",
        ),
        "",
        "# Poll inbox (every hour, wrapper checks configured times)",
        "0 * * * * {wrapper_dir}/openeraseme-poll.sh".format(
            wrapper_dir="{wrapper_dir}"
        ),
        "",
        "# Re-scan (quarterly on 1st of Jan, Apr, Jul, Oct)",
        "{min} {hour} 1 1,4,7,10 * {wrapper_dir}/openeraseme-rescan.sh".format(
            min=config.tick_time.minute,
            hour=config.tick_time.hour,
            wrapper_dir="{wrapper_dir}",
        ),
        "",
    ]
    out["crontab.txt"] = "\n".join(crontab_lines)

    # ── Install / uninstall helpers ──
    install_script = """#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Make wrappers executable
chmod +x "$SCRIPT_DIR"/*.sh

# Install crontab entries (replace our block)
TEMP=$(mktemp)
crontab -l 2>/dev/null | awk '
  /^# OpenEraseMe scheduled tasks$/ { skip=1; next }
  /^# End OpenEraseMe scheduled tasks$/ { skip=0; next }
  skip { next }
  { print }
' > "$TEMP" 2>/dev/null || true

cat "$SCRIPT_DIR/crontab.txt" >> "$TEMP"
# Replace wrapper_dir placeholder
sed -i '' "s|{wrapper_dir}|$SCRIPT_DIR|g" "$TEMP" 2>/dev/null || \
sed -i "s|{wrapper_dir}|$SCRIPT_DIR|g" "$TEMP"

if crontab "$TEMP" 2>/dev/null; then
    echo "Crontab installed. Wrappers in: $SCRIPT_DIR"
else
    echo "Warning: crontab install failed. Manual installation:"
    echo "  crontab $TEMP"
fi
rm -f "$TEMP"
"""
    out["install.sh"] = install_script

    uninstall_script = """#!/usr/bin/env bash
set -euo pipefail

TEMP=$(mktemp)
crontab -l 2>/dev/null | awk '
  /^# OpenEraseMe scheduled tasks$/ { skip=1; next }
  /^# End OpenEraseMe scheduled tasks$/ { skip=0; next }
  skip { next }
  { print }
' > "$TEMP" 2>/dev/null || true

if crontab "$TEMP" 2>/dev/null; then
    echo "OpenEraseMe entries removed from crontab."
else
    echo "No crontab to modify."
fi
rm -f "$TEMP"
"""
    out["uninstall.sh"] = uninstall_script

    return out


# ---------------------------------------------------------------------------
# Launchd (macOS) generator
# ---------------------------------------------------------------------------


def _plist_content(
    label: str,
    wrapper_path: str,
    schedule_interval: str,
    description: str = "",
) -> str:
    """Generate a launchd .plist file content.

    schedule_interval: e.g. "<hourly/>" or "<daily/>" or a calendar interval dict.
    """
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>{label}</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>{wrapper_path}</string>
    </array>
    <key>StartCalendarInterval</key>
    {schedule_interval}
    <key>StandardOutPath</key>
    <string>/tmp/{label}.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/{label}.err</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>OPENERASEME_HEADLESS</key>
        <string>1</string>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>KeepAlive</key>
    <false/>
</dict>
</plist>"""


def _plist_calendar(hour: int, minute: int) -> str:
    return f"""    <dict>
        <key>Hour</key>
        <integer>{hour}</integer>
        <key>Minute</key>
        <integer>{minute}</integer>
    </dict>"""


def generate_launchd(
    config: SchedulerConfig,
    project_dir: str = "",
) -> dict[str, str]:
    """Generate launchd .plist files and wrapper scripts.

    Returns a dict mapping filename -> content.
    """
    bin_path = config.openeraseme_bin or _resolve_bin()
    venv = config.venv_activate or _resolve_venv()
    out: dict[str, str] = {}

    # ── tick (daily) ──
    tick_cmd = f"{bin_path} tick --output json"
    tick_sh = _wrapper_script(tick_cmd, project_dir=project_dir, venv_activate=venv)
    out["openeraseme-tick.sh"] = tick_sh

    tick_calendar = _plist_calendar(config.tick_time.hour, config.tick_time.minute)
    out["com.openeraseme.tick.plist"] = _plist_content(
        label="com.openeraseme.tick",
        wrapper_path="__WRAPPER_DIR__/openeraseme-tick.sh",
        schedule_interval=tick_calendar,
        description="OpenEraseMe daily tick",
    )

    # ── poll-inbox (multiple times daily) ──
    poll_cmd = f"{bin_path} poll-inbox --output json"
    poll_sh = _wrapper_script(poll_cmd, project_dir=project_dir, venv_activate=venv)
    out["openeraseme-poll.sh"] = poll_sh

    # launchd supports StartCalendarInterval as an array of dicts
    poll_entries = "\n".join(
        _plist_calendar(t.hour, t.minute) for t in config.poll_times
    )
    out["com.openeraseme.poll.plist"] = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.openeraseme.poll</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>__WRAPPER_DIR__/openeraseme-poll.sh</string>
    </array>
    <key>StartCalendarInterval</key>
    <array>
{poll_entries}
    </array>
    <key>StandardOutPath</key>
    <string>/tmp/com.openeraseme.poll.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/com.openeraseme.poll.err</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>OPENERASEME_HEADLESS</key>
        <string>1</string>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>KeepAlive</key>
    <false/>
</dict>
</plist>"""

    # ── re-scan (quarterly) ──
    rescan_cmd = f"{bin_path} tick --output json"
    rescan_sh = _wrapper_script(rescan_cmd, project_dir=project_dir, venv_activate=venv)
    out["openeraseme-rescan.sh"] = rescan_sh

    # Quarterly: Jan 1, Apr 1, Jul 1, Oct 1
    quarter_dates = [
        f"""    <dict>
        <key>Month</key>
        <integer>{m}</integer>
        <key>Day</key>
        <integer>1</integer>
        <key>Hour</key>
        <integer>{config.tick_time.hour}</integer>
        <key>Minute</key>
        <integer>{config.tick_time.minute}</integer>
    </dict>"""
        for m in [1, 4, 7, 10]
    ]

    out["com.openeraseme.rescan.plist"] = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>com.openeraseme.rescan</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>__WRAPPER_DIR__/openeraseme-rescan.sh</string>
    </array>
    <key>StartCalendarInterval</key>
    <array>
{chr(10).join(quarter_dates)}
    </array>
    <key>StandardOutPath</key>
    <string>/tmp/com.openeraseme.rescan.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/com.openeraseme.rescan.err</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>OPENERASEME_HEADLESS</key>
        <string>1</string>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>KeepAlive</key>
    <false/>
</dict>
</plist>"""

    # ── Install / uninstall helpers ──
    install_script = """#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

install_plist() {
    local src="$1"
    local name
    name=$(basename "$src")
    local dest="$HOME/Library/LaunchAgents/$name"

    # Replace wrapper dir placeholder
    sed "s|__WRAPPER_DIR__|$SCRIPT_DIR|g" "$src" > /tmp/"$name"
    cp /tmp/"$name" "$dest"
    chmod 644 "$dest"
    chmod +x "$SCRIPT_DIR/openeraseme-tick.sh"
    chmod +x "$SCRIPT_DIR/openeraseme-poll.sh"
    chmod +x "$SCRIPT_DIR/openeraseme-rescan.sh"

    launchctl load "$dest" 2>/dev/null || true
    launchctl start "$(basename "$name" .plist)" 2>/dev/null || true
    echo "Installed: $name"
}

for plist in "$SCRIPT_DIR"/*.plist; do
    [ -f "$plist" ] && install_plist "$plist"
done
echo ""
echo "launchd jobs installed. Wrappers in: $SCRIPT_DIR"
echo "Logs: /tmp/com.openeraseme.*.log"
"""
    out["install.sh"] = install_script

    uninstall_script = """#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

for plist in "$SCRIPT_DIR"/*.plist; do
    [ -f "$plist" ] || continue
    name=$(basename "$plist" .plist)
    dest="$HOME/Library/LaunchAgents/$(basename "$plist")"

    if [ -f "$dest" ]; then
        launchctl unload "$dest" 2>/dev/null || true
        rm -f "$dest"
        echo "Removed: $name"
    fi
done
echo "launchd jobs uninstalled."
"""
    out["uninstall.sh"] = uninstall_script

    return out


# ---------------------------------------------------------------------------
# Systemd generator
# ---------------------------------------------------------------------------


def _systemd_service(
    description: str,
    wrapper_path: str,
    user_service: bool = True,
) -> str:
    """Generate a systemd .service file."""
    return f"""[Unit]
Description={description}
After=network.target

[Service]
Type=oneshot
ExecStart=/bin/bash {wrapper_path}
Environment=OPENERASEME_HEADLESS=1
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
"""


def _systemd_timer(
    description: str,
    on_calendar: str,
) -> str:
    """Generate a systemd .timer file."""
    return f"""[Unit]
Description={description}

[Timer]
OnCalendar={on_calendar}
Persistent=true

[Install]
WantedBy=timers.target
"""


def generate_systemd(
    config: SchedulerConfig,
    project_dir: str = "",
) -> dict[str, str]:
    """Generate systemd service + timer pairs and wrapper scripts.

    Returns a dict mapping filename -> content.
    """
    bin_path = config.openeraseme_bin or _resolve_bin()
    venv = config.venv_activate or _resolve_venv()
    out: dict[str, str] = {}

    # ── tick (daily) ──
    tick_cmd = f"{bin_path} tick --output json"
    out["openeraseme-tick.sh"] = _wrapper_script(
        tick_cmd, project_dir=project_dir, venv_activate=venv
    )
    out["openeraseme-tick.service"] = _systemd_service(
        "OpenEraseMe daily tick",
        "__WRAPPER_DIR__/openeraseme-tick.sh",
    )
    out["openeraseme-tick.timer"] = _systemd_timer(
        "OpenEraseMe daily tick",
        f"Daily-{config.tick_time.hour:02d}:{config.tick_time.minute:02d}",
    )

    # ── poll-inbox (hourly) ──
    poll_cmd = f"{bin_path} poll-inbox --output json"
    out["openeraseme-poll.sh"] = _wrapper_script(
        poll_cmd, project_dir=project_dir, venv_activate=venv
    )
    out["openeraseme-poll.service"] = _systemd_service(
        "OpenEraseMe hourly inbox poll",
        "__WRAPPER_DIR__/openeraseme-poll.sh",
    )
    out["openeraseme-poll.timer"] = _systemd_timer(
        "OpenEraseMe hourly inbox poll",
        "Hourly",
    )

    # ── re-scan (quarterly) ──
    rescan_cmd = f"{bin_path} tick --output json"
    out["openeraseme-rescan.sh"] = _wrapper_script(
        rescan_cmd, project_dir=project_dir, venv_activate=venv
    )
    out["openeraseme-rescan.service"] = _systemd_service(
        "OpenEraseMe quarterly re-scan",
        "__WRAPPER_DIR__/openeraseme-rescan.sh",
    )
    out["openeraseme-rescan.timer"] = _systemd_timer(
        "OpenEraseMe quarterly re-scan",
        "Quarterly",
    )

    # ── Install / uninstall helpers ──
    install_script = """#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
USER_MODE="${1:---user}"

chmod +x "$SCRIPT_DIR"/*.sh

for unit in "$SCRIPT_DIR"/*.service "$SCRIPT_DIR"/*.timer; do
    [ -f "$unit" ] || continue
    name=$(basename "$unit")
    dest="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/$name"
    mkdir -p "$(dirname "$dest")"
    sed "s|__WRAPPER_DIR__|$SCRIPT_DIR|g" "$unit" > "$dest"
    echo "Installed: $name"
done

systemctl $USER_MODE daemon-reload
systemctl $USER_MODE enable --now openeraseme-tick.timer
systemctl $USER_MODE enable --now openeraseme-poll.timer
systemctl $USER_MODE enable --now openeraseme-rescan.timer
echo ""
echo "Systemd timers installed and enabled."
echo "Wrappers in: $SCRIPT_DIR"
echo ""
systemctl $USER_MODE list-timers | grep -i openeraseme || true
"""
    out["install.sh"] = install_script

    uninstall_script = """#!/usr/bin/env bash
set -euo pipefail
USER_MODE="${1:---user}"

for unit in openeraseme-tick openeraseme-poll openeraseme-rescan; do
    systemctl $USER_MODE disable --now "$unit.timer" 2>/dev/null || true
done

for unit in "$SCRIPT_DIR"/*.service "$SCRIPT_DIR"/*.timer; do
    [ -f "$unit" ] || continue
    name=$(basename "$unit")
    dest="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user/$name"
    rm -f "$dest"
    echo "Removed: $name"
done

systemctl $USER_MODE daemon-reload
echo "Systemd timers uninstalled."
"""
    # Add SCRIPT_DIR to the uninstall script
    uninstall_script_fixed = (
        'SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"\n\n'
        + uninstall_script
    )
    out["install.sh"] = install_script
    out["uninstall.sh"] = uninstall_script_fixed

    return out


# ---------------------------------------------------------------------------
# Main API
# ---------------------------------------------------------------------------


def generate_scheduler_configs(
    platform_name: str = "",
    *,
    output_dir: str = "./schedules",
    tick_hour: int = TICK_DEFAULT_TIME.hour,
    tick_minute: int = TICK_DEFAULT_TIME.minute,
    poll_hours: list[int] | None = None,
    project_dir: str = "",
    openeraseme_bin: str = "",
    venv_activate: str = "",
) -> dict[str, str]:
    """Generate scheduler config files for the given platform.

    Args:
        platform_name: One of "cron", "launchd", "systemd", or "" for auto-detect.
        output_dir: Directory to write files into.
        tick_hour: Hour for daily tick (0-23).
        tick_minute: Minute for daily tick (0-59).
        poll_hours: Hours for poll-inbox runs (default: 8, 12, 16, 20).
        project_dir: Project directory for wrapper scripts.
        openeraseme_bin: Path to openeraseme binary.
        venv_activate: Path to virtualenv activate script.

    Returns:
        Dict mapping relative filename -> content.
    """
    if not platform_name:
        platform_name = detect_platform()

    platform_name = platform_name.lower()
    if platform_name not in ("cron", "launchd", "systemd"):
        msg = f"Unsupported platform: {platform_name}. Choose cron, launchd, or systemd."
        raise ValueError(msg)

    poll_times_list = [time(h, 0) for h in (poll_hours or [8, 12, 16, 20])]

    config = SchedulerConfig(
        tick_time=time(tick_hour, tick_minute),
        poll_times=poll_times_list,
        openeraseme_bin=openeraseme_bin or _resolve_bin(),
        venv_activate=venv_activate or _resolve_venv(),
        output_dir=output_dir,
        platform=platform_name,
    )

    generators = {
        "cron": generate_cron,
        "launchd": generate_launchd,
        "systemd": generate_systemd,
    }

    generator = generators[platform_name]
    return generator(config, project_dir=project_dir)


def write_scheduler_files(
    files: dict[str, str],
    output_dir: str,
    *,
    dry_run: bool = False,
) -> list[str]:
    """Write generated scheduler files to disk.

    Args:
        files: Dict of filename -> content from generate_* functions.
        output_dir: Directory to write files into.
        dry_run: If True, only print what would be written.

    Returns:
        List of written file paths.
    """
    out_dir = Path(output_dir).expanduser().resolve()
    written: list[str] = []

    for filename, content in files.items():
        dest = out_dir / filename
        if dry_run:
            logger.info("[dry-run] Would write: %s (%d bytes)", dest, len(content))
            written.append(str(dest))
            continue

        dest.parent.mkdir(parents=True, exist_ok=True)
        dest.write_text(content)

        # Make .sh files executable
        exec_exts = (".sh", ".plist")
        exec_prefixes = ("install", "uninstall")
        if filename.endswith(exec_exts) or filename.startswith(exec_prefixes):
            dest.chmod(dest.stat().st_mode | stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH)

        written.append(str(dest))

    return written


def get_schedule_status(platform_name: str = "") -> dict[str, Any]:
    """Get current schedule status: installed configs and next run times.

    Returns a dict with platform, installed services, last run, next run info.
    """
    if not platform_name:
        platform_name = detect_platform()

    platform_name = platform_name.lower()
    status: dict[str, Any] = {
        "platform": platform_name,
        "installed": [],
        "last_run": None,
        "next_run": None,
    }

    if platform_name == "launchd":
        import subprocess

        for label in ["com.openeraseme.tick", "com.openeraseme.poll", "com.openeraseme.rescan"]:
            plist_path = Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"
            status["installed"].append({
                "label": label,
                "installed": plist_path.exists(),
                "path": str(plist_path) if plist_path.exists() else "",
            })

    elif platform_name == "systemd":
        import subprocess

        for name in ["openeraseme-tick", "openeraseme-poll", "openeraseme-rescan"]:
            try:
                result = subprocess.run(
                    ["systemctl", "--user", "is-enabled", f"{name}.timer"],
                    capture_output=True, text=True, timeout=10,
                )
                enabled = result.returncode == 0
            except (FileNotFoundError, subprocess.TimeoutExpired):
                enabled = False
            status["installed"].append({
                "label": name,
                "installed": enabled,
                "path": f"{name}.timer",
            })

    else:
        # cron: check crontab for our entries
        import subprocess

        try:
            result = subprocess.run(
                ["crontab", "-l"],
                capture_output=True, text=True, timeout=10,
            )
            has_entries = "openeraseme" in result.stdout
            status["installed"].append({
                "label": "cron",
                "installed": has_entries,
                "path": "crontab",
            })
        except (FileNotFoundError, subprocess.TimeoutExpired):
            status["installed"].append({
                "label": "cron",
                "installed": False,
                "error": "crontab not available",
            })

    return status
