"""Cron scheduler configuration generator."""

from __future__ import annotations

from datetime import datetime

from symeraseme.core.scheduler.config import SchedulerConfig, _resolve_bin, _resolve_venv
from symeraseme.core.scheduler.wrapper import _poll_wrapper_script, _wrapper_script


def generate_cron(
    config: SchedulerConfig,
    project_dir: str = "",
) -> dict[str, str]:
    """Generate cron tab entries and wrapper scripts."""
    bin_path = config.symeraseme_bin or _resolve_bin()
    venv = config.venv_activate or _resolve_venv()
    out: dict[str, str] = {}

    out["symeraseme-tick.sh"] = _wrapper_script(
        f"{bin_path} tick --output json",
        project_dir=project_dir,
        venv_activate=venv,
    )
    out["symeraseme-poll.sh"] = _poll_wrapper_script(config, project_dir)

    rescan_cmd = f"{bin_path} tick --output json --dry-run"
    out["symeraseme-rescan.sh"] = _wrapper_script(
        rescan_cmd,
        project_dir=project_dir,
        venv_activate=venv,
    )

    crontab_lines = [
        "# Symaira EraseMe scheduled tasks",
        f"# Generated by symeraseme generate-scheduler on {datetime.now().isoformat()}",
        "",
        f"# Tick (daily at {config.tick_time.hour:02d}:{config.tick_time.minute:02d})",
        (
            f"{config.tick_time.minute} {config.tick_time.hour} * * * "
            f"{{wrapper_dir}}/symeraseme-tick.sh"
        ),
        "",
        "# Poll inbox (every hour, wrapper checks configured times)",
        "0 * * * * {wrapper_dir}/symeraseme-poll.sh",
        "",
        "# Re-scan (quarterly on 1st of Jan, Apr, Jul, Oct)",
        (
            f"{config.tick_time.minute} {config.tick_time.hour} 1 1,4,7,10 * "
            f"{{wrapper_dir}}/symeraseme-rescan.sh"
        ),
        "",
    ]
    out["crontab.txt"] = "\n".join(crontab_lines)

    out["install.sh"] = _cron_install_script()
    out["uninstall.sh"] = _cron_uninstall_script()

    return out


def _cron_install_script() -> str:
    return """#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

# Make wrappers executable
chmod +x "$SCRIPT_DIR"/*.sh

# Install crontab entries (replace our block)
TEMP=$(mktemp)
crontab -l 2>/dev/null | awk '
  /^# Symaira EraseMe scheduled tasks$/ { skip=1; next }
  /^# End Symaira EraseMe scheduled tasks$/ { skip=0; next }
  skip { next }
  { print }
' > "$TEMP" 2>/dev/null || true

cat "$SCRIPT_DIR/crontab.txt" >> "$TEMP"
# Replace wrapper_dir placeholder
sed -i '' "s|{wrapper_dir}|$SCRIPT_DIR|g" "$TEMP" 2>/dev/null || \
sed -i "s|{wrapper_dir}|$SCRIPT_DIR|g" "$TEMP"

if crontab "$TEMP" 2>/dev/null; then
    echo "Crontab installed. Wrappers in: $SCRIPT_DIR"
else
    echo "Warning: crontab install failed. Manual installation:"
    echo "  crontab $TEMP"
fi
rm -f "$TEMP"
"""


def _cron_uninstall_script() -> str:
    return """#!/usr/bin/env bash
set -euo pipefail

TEMP=$(mktemp)
crontab -l 2>/dev/null | awk '
  /^# Symaira EraseMe scheduled tasks$/ { skip=1; next }
  /^# End Symaira EraseMe scheduled tasks$/ { skip=0; next }
  skip { next }
  { print }
' > "$TEMP" 2>/dev/null || true

if crontab "$TEMP" 2>/dev/null; then
    echo "Symaira EraseMe entries removed from crontab."
else
    echo "No crontab to modify."
fi
rm -f "$TEMP"
"""
