"""Wrapper script generation for scheduled commands."""

from __future__ import annotations

import shlex
from pathlib import Path

from symeraseme.core.scheduler.config import SchedulerConfig, _resolve_bin, _resolve_venv

WRAPPER_HEADER = """#!/usr/bin/env bash
# Symaira EraseMe scheduled task wrapper
# Generated by symeraseme generate-scheduler
set -euo pipefail

{venv_block}

export SYMERASEME_HEADLESS=1
export PATH="${{PATH}}:/usr/local/bin:/opt/homebrew/bin"

cd {project_dir}

{command}
"""


def _wrapper_script(
    command: str,
    project_dir: str = "",
    venv_activate: str = "",
) -> str:
    """Generate a shell wrapper script for a scheduler command."""
    if not project_dir:
        project_dir = str(Path.cwd())
    if not venv_activate:
        venv_activate = _resolve_venv()

    venv_block = f"source {shlex.quote(venv_activate)}" if venv_activate else ""

    return WRAPPER_HEADER.format(
        venv_block=venv_block,
        project_dir=shlex.quote(project_dir),
        command=command,
    )


def _poll_wrapper_script(config: SchedulerConfig, project_dir: str) -> str:
    """Generate the poll-inbox wrapper that checks configured times."""
    bin_path = config.symeraseme_bin or _resolve_bin()
    venv = config.venv_activate or _resolve_venv()
    poll_times_str = "|".join(f"{t.hour:02d}:{t.minute:02d}" for t in config.poll_times)

    venv_line = f"source {shlex.quote(venv)}" if venv else ""
    return f"""#!/usr/bin/env bash
set -euo pipefail

{venv_line}
export SYMERASEME_HEADLESS=1
export PATH="${{PATH}}:/usr/local/bin:/opt/homebrew/bin"
cd "{project_dir}"

# Only run at configured poll times
CURRENT_HHMM=$(date +%H:%M)
case "$CURRENT_HHMM" in
{poll_times_str})
    {bin_path} poll-inbox --output json
    ;;
esac
"""
