package scheduler

import (
	"context"
	"errors"
	"os"
	"path/filepath"
	"strings"
	"testing"
)

// installOptionsFor builds an InstallOptions that touches only a private HOME
// and a recording Runner, so these tests never reach the host scheduler.
func installOptionsFor(t *testing.T, home string, platform Platform, replace bool) (InstallOptions, *recordingRunner) {
	t.Helper()
	runner := &recordingRunner{}
	return InstallOptions{
		Config: Config{
			Platform:   platform,
			OutputDir:  filepath.Join(t.TempDir(), "schedules"),
			BinaryPath: "/usr/local/bin/symeraseme",
			ProjectDir: "/srv/erase",
		},
		HomeDir:       home,
		ReplaceLegacy: replace,
		Runner:        runner,
	}, runner
}

func writeUnit(t *testing.T, dir, name, content string) string {
	t.Helper()
	if err := os.MkdirAll(dir, 0o700); err != nil {
		t.Fatal(err)
	}
	path := filepath.Join(dir, name)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
	return path
}

// A unit generated by this implementation uses the same file names as the
// Python era, so name matching alone made `install` refuse its own output and
// re-running `schedule install` could never succeed. The generator marker is
// what separates "ours" from "foreign".
func TestInstallOverItsOwnUnitsDoesNotSelfBlock(t *testing.T) {
	home := t.TempDir()
	native := filepath.Join(home, "Library", "LaunchAgents")
	own := "# Generated by symeraseme generate-scheduler (Go)\n"
	for _, name := range []string{"com.symeraseme.tick.plist", "com.symeraseme.poll.plist", "com.symeraseme.rescan.plist"} {
		writeUnit(t, native, name, own)
	}
	opts, _ := installOptionsFor(t, home, PlatformLaunchd, false)
	result, err := Install(context.Background(), opts)
	if err != nil {
		t.Fatalf("install over its own units = %v, want success", err)
	}
	if result.ReplacementRequired || len(result.Legacy) != 0 {
		t.Fatalf("own units were offered for replacement: %+v", result)
	}
}

func TestInstallTwiceSucceeds(t *testing.T) {
	for _, platform := range []Platform{PlatformLaunchd, PlatformSystemd} {
		t.Run(string(platform), func(t *testing.T) {
			home := t.TempDir()
			opts, _ := installOptionsFor(t, home, platform, false)
			if _, err := Install(context.Background(), opts); err != nil {
				t.Fatalf("first install = %v", err)
			}
			second, err := Install(context.Background(), opts)
			if err != nil {
				t.Fatalf("second install = %v, want success (re-install must be idempotent)", err)
			}
			if len(second.Legacy) != 0 {
				t.Fatalf("second install offered its own units: %+v", second.Legacy)
			}
		})
	}
}

// A unit carrying one of the known names but no generator marker is not ours;
// it must still require explicit replacement consent.
func TestInstallStillRefusesForeignUnits(t *testing.T) {
	home := t.TempDir()
	native := filepath.Join(home, "Library", "LaunchAgents")
	foreign := "<?xml version=\"1.0\"?>\n<plist version=\"1.0\"><dict></dict></plist>\n"
	writeUnit(t, native, "com.symeraseme.tick.plist", foreign)
	opts, _ := installOptionsFor(t, home, PlatformLaunchd, false)
	result, err := Install(context.Background(), opts)
	if !errors.Is(err, ErrLegacyUnits) {
		t.Fatalf("install over a foreign unit = %v, want ErrLegacyUnits", err)
	}
	if !result.ReplacementRequired || len(result.Legacy) != 1 || result.Legacy[0].IsPython {
		t.Fatalf("foreign unit classification = %+v", result.Legacy)
	}
}

// Defect 1: Status resolved `<name>.plist` while Install/Uninstall/the legacy
// scan all used the launchd label, so Status inspected a file that never
// exists and kept reporting a removed unit as installed.
func TestStatusAndUninstallAgreeOnLaunchdPaths(t *testing.T) {
	home := t.TempDir()
	opts, _ := installOptionsFor(t, home, PlatformLaunchd, false)
	if _, err := Install(context.Background(), opts); err != nil {
		t.Fatalf("install = %v", err)
	}
	after, err := Status(context.Background(), opts)
	if err != nil {
		t.Fatalf("status after install = %v", err)
	}
	for _, entry := range after.Entries {
		if !entry.Installed {
			t.Fatalf("status after install: %s reported not installed (path %s)", entry.Label, entry.Path)
		}
		if !strings.HasSuffix(entry.Path, "com.symeraseme."+strings.TrimPrefix(entry.Label, "symeraseme-")+".plist") {
			t.Fatalf("status path %s does not use the launchd label", entry.Path)
		}
	}
	if err := Uninstall(context.Background(), opts); err != nil {
		t.Fatalf("uninstall = %v", err)
	}
	after, err = Status(context.Background(), opts)
	if err != nil {
		t.Fatalf("status after uninstall = %v", err)
	}
	for _, entry := range after.Entries {
		if entry.Installed {
			t.Fatalf("status after uninstall: %s still reported installed at %s", entry.Label, entry.Path)
		}
	}
}

// Status must report legacy units it actually finds; the previous path
// mismatch made the flag permanently false.
func TestStatusReportsLegacyUnits(t *testing.T) {
	home := t.TempDir()
	native := filepath.Join(home, "Library", "LaunchAgents")
	writeUnit(t, native, "com.symeraseme.tick.plist", "python3 -m symeraseme.core.scheduler\n")
	opts, _ := installOptionsFor(t, home, PlatformLaunchd, false)
	result, err := Status(context.Background(), opts)
	if err != nil {
		t.Fatalf("status = %v", err)
	}
	legacy := 0
	for _, entry := range result.Entries {
		if entry.Legacy {
			legacy++
		}
	}
	if legacy != 1 {
		t.Fatalf("status legacy entries = %d, want 1 (%+v)", legacy, result.Entries)
	}
}
