// Package scheduler generates and manages the user-level schedules used by
// symeraseme's tick engine. It intentionally keeps scheduling concerns
// separate from deadlines: the generated jobs invoke the exact symeraseme
// binary selected at install time.
package scheduler

import (
	"context"
	"encoding/xml"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"
)

// Platform is a supported scheduler backend.
type Platform string

const (
	PlatformCron    Platform = "cron"
	PlatformLaunchd Platform = "launchd"
	PlatformSystemd Platform = "systemd"

	wrapperDirPlaceholder = "__WRAPPER_DIR__"
	legacyMarker          = "Generated by symeraseme generate-scheduler"
)

// Config describes the schedule to generate. Zero values select the Python
// integration's defaults, except BinaryPath: an empty BinaryPath resolves to
// the currently running executable so generated jobs never depend on PATH.
type Config struct {
	Platform     Platform
	OutputDir    string
	TickHour     int
	TickMinute   int
	PollHours    []int
	ProjectDir   string
	BinaryPath   string
	VenvActivate string
}

// DefaultConfig returns the schedule used by the Python implementation.
func DefaultConfig() Config {
	return Config{
		TickHour:  10,
		PollHours: []int{8, 12, 16, 20},
		OutputDir: "./schedules",
	}
}

// DetectPlatform selects launchd on macOS, systemd when available on Linux,
// and cron as the portable fallback. Explicit platform selection is preferred
// by callers that need deterministic output.
func DetectPlatform() Platform {
	switch runtime.GOOS {
	case "darwin":
		return PlatformLaunchd
	case "linux":
		if _, err := exec.LookPath("systemctl"); err == nil {
			return PlatformSystemd
		}
	}
	return PlatformCron
}

// ResolveBinaryPath returns an explicit path unchanged. With no override it
// resolves os.Executable, making the generated command independent of PATH or
// the shell's working directory.
func ResolveBinaryPath(explicit string) (string, error) {
	if explicit != "" {
		return explicit, nil
	}
	path, err := os.Executable()
	if err != nil {
		return "", fmt.Errorf("resolve symeraseme executable: %w", err)
	}
	if !filepath.IsAbs(path) {
		path, err = filepath.Abs(path)
		if err != nil {
			return "", fmt.Errorf("make executable path absolute: %w", err)
		}
	}
	return filepath.Clean(path), nil
}

// Generate creates deterministic scheduler files keyed by their relative
// filename. The output contains wrappers, native unit definitions, and
// portable install/uninstall helpers.
func Generate(cfg Config) (map[string]string, error) {
	platform := cfg.Platform
	if platform == "" {
		platform = DetectPlatform()
	}
	platform = Platform(strings.ToLower(string(platform)))
	if !isSupported(platform) {
		return nil, fmt.Errorf("unsupported platform: %s (choose cron, launchd, or systemd)", platform)
	}
	if cfg.TickHour < 0 || cfg.TickHour > 23 || cfg.TickMinute < 0 || cfg.TickMinute > 59 {
		return nil, fmt.Errorf("tick time must be a valid 24-hour time")
	}
	pollHours := append([]int(nil), cfg.PollHours...)
	if len(pollHours) == 0 {
		pollHours = []int{8, 12, 16, 20}
	}
	for _, hour := range pollHours {
		if hour < 0 || hour > 23 {
			return nil, fmt.Errorf("poll hour must be between 0 and 23: %d", hour)
		}
	}
	binaryPath, err := ResolveBinaryPath(cfg.BinaryPath)
	if err != nil {
		return nil, err
	}
	projectDir := cfg.ProjectDir
	if projectDir == "" {
		projectDir, err = os.Getwd()
		if err != nil {
			return nil, fmt.Errorf("resolve project directory: %w", err)
		}
	}

	switch platform {
	case PlatformCron:
		return generateCron(cfg, binaryPath, projectDir, pollHours), nil
	case PlatformLaunchd:
		return generateLaunchd(cfg, binaryPath, projectDir, pollHours), nil
	case PlatformSystemd:
		return generateSystemd(cfg, binaryPath, projectDir, pollHours), nil
	default:
		panic("unsupported platform passed validation")
	}
}

// GenerateSchedulerConfigs is an explicit alias matching the Python service
// name and is useful to callers porting command handlers.
func GenerateSchedulerConfigs(cfg Config) (map[string]string, error) {
	return Generate(cfg)
}

func isSupported(platform Platform) bool {
	return platform == PlatformCron || platform == PlatformLaunchd || platform == PlatformSystemd
}

func shellQuote(value string) string {
	return "'" + strings.ReplaceAll(value, "'", "'\\''") + "'"
}

func wrapper(command []string, projectDir, venv string) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Symaira EraseMe scheduled task wrapper\n")
	b.WriteString("# Generated by symeraseme generate-scheduler (Go)\n")
	b.WriteString("set -euo pipefail\n\n")
	if venv != "" {
		b.WriteString("source ")
		b.WriteString(shellQuote(venv))
		b.WriteString("\n\n")
	}
	b.WriteString("export SYMERASEME_HEADLESS=1\n")
	b.WriteString("cd ")
	b.WriteString(shellQuote(projectDir))
	b.WriteString("\n\nexec")
	for _, arg := range command {
		b.WriteByte(' ')
		b.WriteString(shellQuote(arg))
	}
	b.WriteString("\n")
	return b.String()
}

func pollWrapper(binaryPath, projectDir, venv string, pollHours []int) string {
	var b strings.Builder
	b.WriteString("#!/usr/bin/env bash\n")
	b.WriteString("# Symaira EraseMe scheduled inbox poll wrapper\n")
	b.WriteString("# Generated by symeraseme generate-scheduler (Go)\n")
	b.WriteString("set -euo pipefail\n\n")
	if venv != "" {
		b.WriteString("source ")
		b.WriteString(shellQuote(venv))
		b.WriteString("\n")
	}
	b.WriteString("export SYMERASEME_HEADLESS=1\n")
	b.WriteString("cd ")
	b.WriteString(shellQuote(projectDir))
	b.WriteString("\n\n")
	b.WriteString("CURRENT_HHMM=$(date +%H:%M)\n")
	b.WriteString("case \"$CURRENT_HHMM\" in\n")
	for i, hour := range pollHours {
		if i > 0 {
			b.WriteByte('|')
		}
		fmt.Fprintf(&b, "%02d:00", hour)
	}
	b.WriteString(")\n    exec ")
	b.WriteString(shellQuote(binaryPath))
	b.WriteString(" poll-inbox --output json\n    ;;\nesac\n")
	return b.String()
}

func generateCron(cfg Config, binaryPath, projectDir string, pollHours []int) map[string]string {
	files := map[string]string{
		"symeraseme-tick.sh":   wrapper([]string{binaryPath, "tick", "--output", "json"}, projectDir, cfg.VenvActivate),
		"symeraseme-poll.sh":   pollWrapper(binaryPath, projectDir, cfg.VenvActivate, pollHours),
		"symeraseme-rescan.sh": wrapper([]string{binaryPath, "tick", "--output", "json", "--dry-run"}, projectDir, cfg.VenvActivate),
		"install.sh":           cronInstallScript(),
		"uninstall.sh":         cronUninstallScript(),
	}
	files["crontab.txt"] = cronTab(cfg.TickHour, cfg.TickMinute)
	return files
}

func cronTab(hour, minute int) string {
	return fmt.Sprintf(`# Symaira EraseMe scheduled tasks
# Generated by symeraseme generate-scheduler (Go)

# Tick (daily at %02d:%02d)
%d %d * * * {wrapper_dir}/symeraseme-tick.sh

# Poll inbox (hourly wrapper checks configured times)
0 * * * * {wrapper_dir}/symeraseme-poll.sh

# Re-scan (quarterly on 1st of Jan, Apr, Jul, Oct)
%d %d 1 1,4,7,10 * {wrapper_dir}/symeraseme-rescan.sh

# End Symaira EraseMe scheduled tasks
`, hour, minute, minute, hour, minute, hour)
}

func launchdCalendar(hour, minute int) string {
	return fmt.Sprintf(`    <dict>
        <key>Hour</key>
        <integer>%d</integer>
        <key>Minute</key>
        <integer>%d</integer>
    </dict>`, hour, minute)
}

func launchdQuarterly(hour, minute int) string {
	months := []int{1, 4, 7, 10}
	entries := make([]string, 0, len(months))
	for _, month := range months {
		entries = append(entries, fmt.Sprintf(`    <dict>
        <key>Month</key>
        <integer>%d</integer>
        <key>Day</key>
        <integer>1</integer>
        <key>Hour</key>
        <integer>%d</integer>
        <key>Minute</key>
        <integer>%d</integer>
    </dict>`, month, hour, minute))
	}
	return strings.Join(entries, "\n")
}

func plistString(value string) string {
	var b strings.Builder
	_ = xml.EscapeText(&b, []byte(value))
	return b.String()
}

func plist(label, wrapperPath, intervals string, array bool) string {
	if array {
		intervals = "    <array>\n" + intervals + "\n    </array>"
	} else {
		intervals = "    " + intervals
	}
	return fmt.Sprintf(`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>Label</key>
    <string>%s</string>
    <key>ProgramArguments</key>
    <array>
        <string>/bin/bash</string>
        <string>%s</string>
    </array>
    <key>StartCalendarInterval</key>
%s
    <key>StandardOutPath</key>
    <string>/tmp/%s.log</string>
    <key>StandardErrorPath</key>
    <string>/tmp/%s.err</string>
    <key>EnvironmentVariables</key>
    <dict>
        <key>SYMERASEME_HEADLESS</key>
        <string>1</string>
    </dict>
    <key>RunAtLoad</key>
    <false/>
    <key>KeepAlive</key>
    <false/>
</dict>
</plist>
`, plistString(label), plistString(wrapperPath), intervals, plistString(label), plistString(label))
}

func generateLaunchd(cfg Config, binaryPath, projectDir string, pollHours []int) map[string]string {
	pollIntervals := make([]string, 0, len(pollHours))
	for _, hour := range pollHours {
		pollIntervals = append(pollIntervals, launchdCalendar(hour, 0))
	}
	return map[string]string{
		"symeraseme-tick.sh":          wrapper([]string{binaryPath, "tick", "--output", "json"}, projectDir, cfg.VenvActivate),
		"com.symeraseme.tick.plist":   plist("com.symeraseme.tick", wrapperDirPlaceholder+"/symeraseme-tick.sh", launchdCalendar(cfg.TickHour, cfg.TickMinute), false),
		"symeraseme-poll.sh":          wrapper([]string{binaryPath, "poll-inbox", "--output", "json"}, projectDir, cfg.VenvActivate),
		"com.symeraseme.poll.plist":   plist("com.symeraseme.poll", wrapperDirPlaceholder+"/symeraseme-poll.sh", strings.Join(pollIntervals, "\n"), true),
		"symeraseme-rescan.sh":        wrapper([]string{binaryPath, "tick", "--output", "json"}, projectDir, cfg.VenvActivate),
		"com.symeraseme.rescan.plist": plist("com.symeraseme.rescan", wrapperDirPlaceholder+"/symeraseme-rescan.sh", launchdQuarterly(cfg.TickHour, cfg.TickMinute), true),
		"install.sh":                  launchdInstallScript(),
		"uninstall.sh":                launchdUninstallScript(),
	}
}

func systemdService(description, wrapperPath string) string {
	return fmt.Sprintf(`[Unit]
Description=%s
After=network-online.target

[Service]
Type=oneshot
ExecStart=/bin/bash "%s"
Environment=SYMERASEME_HEADLESS=1
StandardOutput=journal
StandardError=journal

[Install]
WantedBy=default.target
`, description, wrapperPath)
}

func systemdTimer(description, serviceName, calendar string) string {
	return fmt.Sprintf(`[Unit]
Description=%s

[Timer]
Unit=%s.service
OnCalendar=%s
Persistent=true

[Install]
WantedBy=timers.target
`, description, serviceName, calendar)
}

func generateSystemd(cfg Config, binaryPath, projectDir string, pollHours []int) map[string]string {
	_ = pollHours // systemd invokes the poll wrapper hourly, matching Python.
	return map[string]string{
		"symeraseme-tick.sh":        wrapper([]string{binaryPath, "tick", "--output", "json"}, projectDir, cfg.VenvActivate),
		"symeraseme-tick.service":   systemdService("Symaira EraseMe daily tick", wrapperDirPlaceholder+"/symeraseme-tick.sh"),
		"symeraseme-tick.timer":     systemdTimer("Symaira EraseMe daily tick", "symeraseme-tick", fmt.Sprintf("Daily-%02d:%02d", cfg.TickHour, cfg.TickMinute)),
		"symeraseme-poll.sh":        wrapper([]string{binaryPath, "poll-inbox", "--output", "json"}, projectDir, cfg.VenvActivate),
		"symeraseme-poll.service":   systemdService("Symaira EraseMe hourly inbox poll", wrapperDirPlaceholder+"/symeraseme-poll.sh"),
		"symeraseme-poll.timer":     systemdTimer("Symaira EraseMe hourly inbox poll", "symeraseme-poll", "Hourly"),
		"symeraseme-rescan.sh":      wrapper([]string{binaryPath, "tick", "--output", "json"}, projectDir, cfg.VenvActivate),
		"symeraseme-rescan.service": systemdService("Symaira EraseMe quarterly re-scan", wrapperDirPlaceholder+"/symeraseme-rescan.sh"),
		"symeraseme-rescan.timer":   systemdTimer("Symaira EraseMe quarterly re-scan", "symeraseme-rescan", "Quarterly"),
		"install.sh":                systemdInstallScript(),
		"uninstall.sh":              systemdUninstallScript(),
	}
}

func blockRemovalScript() string {
	return `awk '
  /^# Symaira EraseMe scheduled tasks$/ { skip=1; next }
  /^# End Symaira EraseMe scheduled tasks$/ { skip=0; next }
  skip { next }
  { print }
'`
}

func cronInstallScript() string {
	return `#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
chmod +x "$SCRIPT_DIR"/*.sh
TEMP=$(mktemp)
trap 'rm -f "$TEMP"' EXIT
(crontab -l 2>/dev/null || true) | ` + blockRemovalScript() + ` > "$TEMP"
sed "s|{wrapper_dir}|$SCRIPT_DIR|g" "$SCRIPT_DIR/crontab.txt" >> "$TEMP"
crontab "$TEMP"
printf 'Crontab installed. Wrappers in: %s\n' "$SCRIPT_DIR"
`
}

func cronUninstallScript() string {
	return `#!/usr/bin/env bash
set -euo pipefail
TEMP=$(mktemp)
trap 'rm -f "$TEMP"' EXIT
(crontab -l 2>/dev/null || true) | ` + blockRemovalScript() + ` > "$TEMP"
crontab "$TEMP"
printf '%s\n' 'Symaira EraseMe entries removed from crontab.'
`
}

func launchdInstallScript() string {
	return `#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEST="$HOME/Library/LaunchAgents"
mkdir -p "$DEST"
for plist in "$SCRIPT_DIR"/*.plist; do
  [ -f "$plist" ] || continue
  name=$(basename "$plist")
  sed "s|__WRAPPER_DIR__|$SCRIPT_DIR|g" "$plist" > "$DEST/$name"
  chmod 644 "$DEST/$name"
  launchctl unload "$DEST/$name" 2>/dev/null || true
  launchctl load "$DEST/$name"
done
chmod +x "$SCRIPT_DIR"/*.sh
printf '%s\n' 'launchd jobs installed.'
`
}

func launchdUninstallScript() string {
	return `#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
for plist in "$SCRIPT_DIR"/*.plist; do
  [ -f "$plist" ] || continue
  name=$(basename "$plist")
  dest="$HOME/Library/LaunchAgents/$name"
  launchctl unload "$dest" 2>/dev/null || true
  rm -f "$dest"
done
printf '%s\n' 'launchd jobs uninstalled.'
`
}

func systemdInstallScript() string {
	return `#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEST="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
mkdir -p "$DEST"
chmod +x "$SCRIPT_DIR"/*.sh
for unit in "$SCRIPT_DIR"/*.service "$SCRIPT_DIR"/*.timer; do
  [ -f "$unit" ] || continue
  name=$(basename "$unit")
  sed "s|__WRAPPER_DIR__|$SCRIPT_DIR|g" "$unit" > "$DEST/$name"
done
systemctl --user daemon-reload
for timer in symeraseme-tick symeraseme-poll symeraseme-rescan; do
  systemctl --user enable --now "$timer.timer"
done
printf '%s\n' 'Systemd timers installed and enabled.'
`
}

func systemdUninstallScript() string {
	return `#!/usr/bin/env bash
set -euo pipefail
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
DEST="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
for timer in symeraseme-tick symeraseme-poll symeraseme-rescan; do
  systemctl --user disable --now "$timer.timer" 2>/dev/null || true
done
for unit in "$SCRIPT_DIR"/*.service "$SCRIPT_DIR"/*.timer; do
  [ -f "$unit" ] || continue
  rm -f "$DEST/$(basename "$unit")"
done
systemctl --user daemon-reload
printf '%s\n' 'Systemd timers uninstalled.'
`
}

// WriteFiles writes generated files in sorted order and returns absolute paths.
// Only relative paths are accepted, preventing a caller from escaping outputDir.
func WriteFiles(outputDir string, files map[string]string) ([]string, error) {
	if outputDir == "" {
		return nil, errors.New("output directory must not be empty")
	}
	root, err := filepath.Abs(outputDir)
	if err != nil {
		return nil, fmt.Errorf("resolve output directory: %w", err)
	}
	if err := os.MkdirAll(root, 0o755); err != nil {
		return nil, fmt.Errorf("create output directory: %w", err)
	}
	names := make([]string, 0, len(files))
	for name := range files {
		clean := filepath.Clean(name)
		if clean == "." || filepath.IsAbs(name) || clean == ".." || strings.HasPrefix(clean, ".."+string(filepath.Separator)) {
			return nil, fmt.Errorf("invalid generated filename: %q", name)
		}
		names = append(names, name)
	}
	sort.Strings(names)
	written := make([]string, 0, len(names))
	for _, name := range names {
		path := filepath.Join(root, filepath.Clean(name))
		mode := os.FileMode(0o644)
		if strings.HasSuffix(name, ".sh") {
			mode = 0o755
		}
		if err := os.WriteFile(path, []byte(files[name]), mode); err != nil {
			return nil, fmt.Errorf("write %s: %w", path, err)
		}
		written = append(written, path)
	}
	return written, nil
}

// WriteSchedulerFiles is an alias matching the Python service name.
func WriteSchedulerFiles(outputDir string, files map[string]string) ([]string, error) {
	return WriteFiles(outputDir, files)
}

// LegacyUnit describes an existing scheduler definition that must be
// explicitly replaced before installation. Existing known unit paths are
// reported even when their contents do not contain Python, preventing silent
// duplication with manually edited legacy schedules.
type LegacyUnit struct {
	Platform Platform
	Kind     string
	Name     string
	Path     string
	IsPython bool
	Reason   string
}

// ErrLegacyUnits signals that installation was refused to avoid overwriting
// an existing Python/legacy schedule without explicit replacement consent.
var ErrLegacyUnits = errors.New("legacy scheduler units detected; replacement was not requested")

var legacyNames = []string{
	"com.symeraseme.tick.plist",
	"com.symeraseme.poll.plist",
	"com.symeraseme.rescan.plist",
	"symeraseme-tick.service",
	"symeraseme-tick.timer",
	"symeraseme-poll.service",
	"symeraseme-poll.timer",
	"symeraseme-rescan.service",
	"symeraseme-rescan.timer",
}

// DetectLegacyPythonUnit reports whether a file contains markers associated
// with the Python scheduler. It is content-based and safe for missing files.
func DetectLegacyPythonUnit(path string) (bool, error) {
	data, err := os.ReadFile(path)
	if err != nil {
		if os.IsNotExist(err) {
			return false, nil
		}
		return false, err
	}
	return isPythonSchedulerContent(string(data)), nil
}

func isPythonSchedulerContent(content string) bool {
	lower := strings.ToLower(content)
	markers := []string{"python", "site-packages", "symeraseme.core.scheduler", "uv run", "venv/bin/activate"}
	for _, marker := range markers {
		if strings.Contains(lower, marker) {
			return true
		}
	}
	return strings.Contains(content, legacyMarker) && !strings.Contains(content, legacyMarker+" (Go)")
}

// ScanLegacyPythonUnits scans the native per-user unit locations. Existing
// known Symaira unit names are returned as replacement candidates; IsPython
// distinguishes units whose contents explicitly point at the Python runtime.
func ScanLegacyPythonUnits(home string, platform Platform) ([]LegacyUnit, error) {
	if home == "" {
		var err error
		home, err = os.UserHomeDir()
		if err != nil {
			return nil, fmt.Errorf("resolve home directory: %w", err)
		}
	}
	platform = Platform(strings.ToLower(string(platform)))
	if platform == "" {
		platform = DetectPlatform()
	}
	var root string
	var names []string
	var kind string
	switch platform {
	case PlatformLaunchd:
		root, names, kind = filepath.Join(home, "Library", "LaunchAgents"), legacyNames[:3], "launchd"
	case PlatformSystemd:
		root, names, kind = filepath.Join(home, ".config", "systemd", "user"), legacyNames[3:], "systemd"
	default:
		return nil, nil // cron entries are inspected by Status/Install via crontab.
	}
	units := make([]LegacyUnit, 0)
	for _, name := range names {
		path := filepath.Join(root, name)
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, fmt.Errorf("read legacy unit %s: %w", path, err)
		}
		isPython := isPythonSchedulerContent(string(data))
		reason := "existing Symaira scheduler unit; explicit replacement required"
		if isPython {
			reason = "existing Python scheduler unit; explicit replacement required"
		}
		units = append(units, LegacyUnit{Platform: platform, Kind: kind, Name: name, Path: path, IsPython: isPython, Reason: reason})
	}
	return units, nil
}

// DetectLegacyPythonUnits is a convenience scanner for caller-provided paths.
func DetectLegacyPythonUnits(paths []string) ([]LegacyUnit, error) {
	units := make([]LegacyUnit, 0)
	for _, path := range paths {
		data, err := os.ReadFile(path)
		if err != nil {
			if os.IsNotExist(err) {
				continue
			}
			return nil, err
		}
		if !isPythonSchedulerContent(string(data)) {
			continue
		}
		units = append(units, LegacyUnit{Path: path, IsPython: true, Reason: "existing Python scheduler unit; explicit replacement required"})
	}
	return units, nil
}

// Runner executes platform commands. Tests can inject a recording runner;
// production uses ExecRunner.
type Runner interface {
	Run(context.Context, string, ...string) ([]byte, error)
}

type ExecRunner struct{}

func (ExecRunner) Run(ctx context.Context, name string, args ...string) ([]byte, error) {
	return exec.CommandContext(ctx, name, args...).CombinedOutput()
}

// InstallOptions controls installation. ReplaceLegacy must be true to replace
// any existing known unit; this makes upgrades explicit and non-destructive.
type InstallOptions struct {
	Config        Config
	HomeDir       string
	XDGConfigHome string
	ReplaceLegacy bool
	Runner        Runner
}

// InstallResult reports generated output and any legacy candidates found.
type InstallResult struct {
	Platform            Platform
	OutputDir           string
	Files               []string
	Legacy              []LegacyUnit
	ReplacementRequired bool
}

func installRoot(opts InstallOptions, platform Platform) (string, error) {
	home := opts.HomeDir
	if home == "" {
		var err error
		home, err = os.UserHomeDir()
		if err != nil {
			return "", err
		}
	}
	if platform == PlatformLaunchd {
		return filepath.Join(home, "Library", "LaunchAgents"), nil
	}
	configHome := opts.XDGConfigHome
	if configHome == "" && opts.HomeDir == "" {
		configHome = os.Getenv("XDG_CONFIG_HOME")
	}
	if configHome == "" {
		configHome = filepath.Join(home, ".config")
	}
	return filepath.Join(configHome, "systemd", "user"), nil
}

func replaceWrapperPlaceholder(content, outputDir string) string {
	return strings.ReplaceAll(content, wrapperDirPlaceholder, outputDir)
}

// Install writes generated files and installs native units. Cron installation
// updates only the marked Symaira block; launchd/systemd install user-level
// files and then invoke their native reload/enable commands.
func Install(ctx context.Context, opts InstallOptions) (InstallResult, error) {
	cfg := opts.Config
	if cfg.Platform == "" {
		cfg.Platform = DetectPlatform()
	}
	platform := Platform(strings.ToLower(string(cfg.Platform)))
	if !isSupported(platform) {
		return InstallResult{Platform: platform}, fmt.Errorf("unsupported platform: %s", platform)
	}
	if cfg.OutputDir == "" {
		cfg.OutputDir = DefaultConfig().OutputDir
	}
	legacy, err := ScanLegacyPythonUnits(opts.HomeDir, platform)
	if err != nil {
		return InstallResult{Platform: platform}, err
	}
	result := InstallResult{Platform: platform, OutputDir: cfg.OutputDir, Legacy: legacy, ReplacementRequired: len(legacy) > 0}
	if len(legacy) > 0 && !opts.ReplaceLegacy {
		return result, ErrLegacyUnits
	}
	files, err := Generate(cfg)
	if err != nil {
		return result, err
	}
	written, err := WriteFiles(cfg.OutputDir, files)
	if err != nil {
		return result, err
	}
	result.Files = written
	for _, unit := range legacy {
		if err := os.Remove(unit.Path); err != nil && !os.IsNotExist(err) {
			return result, fmt.Errorf("remove legacy unit %s: %w", unit.Path, err)
		}
	}

	runner := opts.Runner
	if runner == nil {
		runner = ExecRunner{}
	}
	if platform == PlatformCron {
		return result, installCron(ctx, runner, files["crontab.txt"], cfg.OutputDir)
	}
	root, err := installRoot(opts, platform)
	if err != nil {
		return result, err
	}
	if err := os.MkdirAll(root, 0o700); err != nil {
		return result, fmt.Errorf("create native unit directory: %w", err)
	}
	if err := installNativeUnits(files, root, cfg.OutputDir, platform); err != nil {
		return result, err
	}
	if platform == PlatformLaunchd {
		for _, name := range []string{"com.symeraseme.tick.plist", "com.symeraseme.poll.plist", "com.symeraseme.rescan.plist"} {
			path := filepath.Join(root, name)
			_, _ = runner.Run(ctx, "launchctl", "unload", path)
			if _, err := runner.Run(ctx, "launchctl", "load", path); err != nil {
				return result, fmt.Errorf("load launchd unit %s: %w", name, err)
			}
		}
		return result, nil
	}
	if _, err := runner.Run(ctx, "systemctl", "--user", "daemon-reload"); err != nil {
		return result, fmt.Errorf("systemd daemon-reload: %w", err)
	}
	for _, name := range []string{"symeraseme-tick", "symeraseme-poll", "symeraseme-rescan"} {
		if _, err := runner.Run(ctx, "systemctl", "--user", "enable", "--now", name+".timer"); err != nil {
			return result, fmt.Errorf("enable systemd timer %s: %w", name, err)
		}
	}
	return result, nil
}

func installCron(ctx context.Context, runner Runner, content, outputDir string) error {
	existing, _ := runner.Run(ctx, "crontab", "-l")
	temp, err := os.CreateTemp(outputDir, ".crontab-*")
	if err != nil {
		return fmt.Errorf("create crontab staging file: %w", err)
	}
	path := temp.Name()
	defer os.Remove(path)
	updated := removeCronBlock(string(existing))
	if updated != "" && !strings.HasSuffix(updated, "\n") {
		updated += "\n"
	}
	updated += contentWithWrapperDir(content, outputDir)
	if _, err := temp.WriteString(updated); err != nil {
		temp.Close()
		return fmt.Errorf("write crontab staging file: %w", err)
	}
	if err := temp.Close(); err != nil {
		return fmt.Errorf("close crontab staging file: %w", err)
	}
	if _, err := runner.Run(ctx, "crontab", path); err != nil {
		return fmt.Errorf("install crontab: %w", err)
	}
	return nil
}

func contentWithWrapperDir(content, outputDir string) string {
	return strings.ReplaceAll(content, "{wrapper_dir}", outputDir)
}

func installNativeUnits(files map[string]string, root, outputDir string, platform Platform) error {
	extension := ".plist"
	if platform == PlatformSystemd {
		extension = ".service"
	}
	names := make([]string, 0, len(files))
	for name := range files {
		if strings.HasSuffix(name, extension) || (platform == PlatformSystemd && strings.HasSuffix(name, ".timer")) {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		path := filepath.Join(root, name)
		if err := os.WriteFile(path, []byte(replaceWrapperPlaceholder(files[name], outputDir)), 0o644); err != nil {
			return fmt.Errorf("write native unit %s: %w", path, err)
		}
	}
	return nil
}

// StatusEntry is the state of one scheduler unit.
type StatusEntry struct {
	Label     string
	Installed bool
	Active    bool
	Path      string
	Legacy    bool
	Error     string
}

// StatusResult reports scheduler state without requiring a platform runtime in
// generation tests. Native command errors are retained per entry.
type StatusResult struct {
	Platform Platform
	Entries  []StatusEntry
}

// Status checks user-level scheduler state.
func Status(ctx context.Context, opts InstallOptions) (StatusResult, error) {
	platform := opts.Config.Platform
	if platform == "" {
		platform = DetectPlatform()
	}
	platform = Platform(strings.ToLower(string(platform)))
	if !isSupported(platform) {
		return StatusResult{Platform: platform}, fmt.Errorf("unsupported platform: %s", platform)
	}
	runner := opts.Runner
	if runner == nil {
		runner = ExecRunner{}
	}
	if platform == PlatformCron {
		out, err := runner.Run(ctx, "crontab", "-l")
		entry := StatusEntry{Label: "cron", Path: "crontab"}
		if err != nil {
			entry.Error = "crontab not available or no crontab installed"
		} else {
			entry.Installed = strings.Contains(string(out), "# Symaira EraseMe scheduled tasks")
			entry.Legacy = isPythonSchedulerContent(string(out))
		}
		return StatusResult{Platform: platform, Entries: []StatusEntry{entry}}, nil
	}
	root, err := installRoot(opts, platform)
	if err != nil {
		return StatusResult{Platform: platform}, err
	}
	units, err := ScanLegacyPythonUnits(opts.HomeDir, platform)
	if err != nil {
		return StatusResult{Platform: platform}, err
	}
	legacyByPath := make(map[string]bool, len(units))
	for _, unit := range units {
		legacyByPath[unit.Path] = unit.IsPython
	}
	names := []string{"symeraseme-tick", "symeraseme-poll", "symeraseme-rescan"}
	entries := make([]StatusEntry, 0, len(names))
	for _, name := range names {
		ext := ".plist"
		if platform == PlatformSystemd {
			ext = ".timer"
		}
		path := filepath.Join(root, name+ext)
		entry := StatusEntry{Label: name, Path: path}
		_, statErr := os.Stat(path)
		entry.Installed = statErr == nil
		entry.Legacy = legacyByPath[path]
		if platform == PlatformLaunchd {
			out, runErr := runner.Run(ctx, "launchctl", "list", nameToLaunchdLabel(name))
			entry.Active = runErr == nil && strings.Contains(string(out), nameToLaunchdLabel(name))
			if runErr != nil && entry.Installed {
				entry.Error = "launchctl could not confirm active state"
			}
		} else {
			out, runErr := runner.Run(ctx, "systemctl", "--user", "is-active", name+".timer")
			entry.Active = runErr == nil && strings.TrimSpace(string(out)) == "active"
			if runErr != nil && entry.Installed {
				entry.Error = "systemctl could not confirm active state"
			}
		}
		entries = append(entries, entry)
	}
	return StatusResult{Platform: platform, Entries: entries}, nil
}

func nameToLaunchdLabel(name string) string {
	return "com.symeraseme." + strings.TrimPrefix(name, "symeraseme-")
}

// Uninstall removes native units or the marked cron block. It never removes
// generated wrappers from OutputDir, which keeps uninstall reversible.
func Uninstall(ctx context.Context, opts InstallOptions) error {
	platform := opts.Config.Platform
	if platform == "" {
		platform = DetectPlatform()
	}
	platform = Platform(strings.ToLower(string(platform)))
	if !isSupported(platform) {
		return fmt.Errorf("unsupported platform: %s", platform)
	}
	runner := opts.Runner
	if runner == nil {
		runner = ExecRunner{}
	}
	if platform == PlatformCron {
		out, err := runner.Run(ctx, "crontab", "-l")
		if err != nil {
			return nil
		}
		temp, err := os.CreateTemp(os.TempDir(), ".symeraseme-crontab-*")
		if err != nil {
			return err
		}
		path := temp.Name()
		defer os.Remove(path)
		cleaned := removeCronBlock(string(out))
		if _, err := temp.WriteString(cleaned); err != nil {
			temp.Close()
			return err
		}
		if err := temp.Close(); err != nil {
			return err
		}
		_, err = runner.Run(ctx, "crontab", path)
		return err
	}
	root, err := installRoot(opts, platform)
	if err != nil {
		return err
	}
	names := []string{"symeraseme-tick", "symeraseme-poll", "symeraseme-rescan"}
	if platform == PlatformLaunchd {
		for _, name := range names {
			path := filepath.Join(root, nameToLaunchdLabel(name)+".plist")
			_, _ = runner.Run(ctx, "launchctl", "unload", path)
			if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
				return err
			}
		}
		return nil
	}
	for _, name := range names {
		_, _ = runner.Run(ctx, "systemctl", "--user", "disable", "--now", name+".timer")
		for _, ext := range []string{".service", ".timer"} {
			path := filepath.Join(root, name+ext)
			if err := os.Remove(path); err != nil && !os.IsNotExist(err) {
				return err
			}
		}
	}
	_, _ = runner.Run(ctx, "systemctl", "--user", "daemon-reload")
	return nil
}

func removeCronBlock(content string) string {
	lines := strings.Split(content, "\n")
	out := make([]string, 0, len(lines))
	skip := false
	for _, line := range lines {
		switch line {
		case "# Symaira EraseMe scheduled tasks":
			skip = true
		case "# End Symaira EraseMe scheduled tasks":
			skip = false
		default:
			if !skip {
				out = append(out, line)
			}
		}
	}
	return strings.Join(out, "\n")
}
