// Command scheduler is the committed Go scheduler-generation provenance
// oracle.
//
// Unlike the config oracle, scheduler.Generate and scheduler.WriteFiles read
// no environment or filesystem state beyond their explicit Config argument,
// so no isolated-process sandbox is required here: the oracle calls the
// production internal/scheduler package in-process for a fixed set of named
// cases and dumps the resulting byte-exact file maps as JSON.
//
// legacyCases additionally exercises DetectLegacyPythonUnit, which does read
// a file — but only one this oracle writes itself from a fixed content
// string immediately before the call, so the result is still fully
// deterministic and needs no isolated-process sandbox either.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"runtime"
	"sort"

	"github.com/danieljustus/symaira-eraseme/internal/scheduler"
)

const (
	sourceRevision = "ef1f7bcbaf748b490eeeb0bc4ef879cb2f536de6"
	sourceSHA256   = "d936e2fea18f2f36e4801b3812d2c5c5d379c33423680e35c74d3d7a4e5f8860"
	oracleSchema   = "symaira-eraseme.scheduler-parity.v1"
)

type provenance struct {
	SourceRevision string `json:"source_revision"`
	SourcePath     string `json:"source_path"`
	SourceSHA256   string `json:"source_sha256"`
	Schema         string `json:"schema"`
}

type oracleOutput struct {
	Provenance  provenance                   `json:"provenance"`
	Cases       map[string]map[string]string `json:"cases"`
	LegacyCases map[string]legacyCaseResult  `json:"legacy_cases"`
}

type legacyCaseResult struct {
	Content  string `json:"content"`
	IsPython bool   `json:"is_python"`
}

func main() {
	source := oracleSourcePath()
	schedulerSource := filepath.Clean(filepath.Join(filepath.Dir(source), "../../../../internal/scheduler/scheduler.go"))
	if err := verifySourceHash(schedulerSource, sourceSHA256); err != nil {
		fatal("oracle source provenance verification failed: " + err.Error())
	}

	cases := map[string]scheduler.Config{
		"deterministic_custom_cron": {
			Platform:   scheduler.PlatformCron,
			ProjectDir: "/work/project with spaces",
			BinaryPath: "/opt/symaira/bin/symeraseme",
			TickHour:   6,
			TickMinute: 45,
			PollHours:  []int{8, 20},
		},
		"all_backends_cron": {
			Platform:   scheduler.PlatformCron,
			BinaryPath: "/usr/local/bin/symeraseme",
			ProjectDir: "/srv/erase",
			TickHour:   10,
			PollHours:  []int{8, 12, 16, 20},
		},
		"all_backends_launchd": {
			Platform:   scheduler.PlatformLaunchd,
			BinaryPath: "/usr/local/bin/symeraseme",
			ProjectDir: "/srv/erase",
			TickHour:   10,
			PollHours:  []int{8, 12, 16, 20},
		},
		"all_backends_systemd": {
			Platform:   scheduler.PlatformSystemd,
			BinaryPath: "/usr/local/bin/symeraseme",
			ProjectDir: "/srv/erase",
			TickHour:   10,
			PollHours:  []int{8, 12, 16, 20},
		},
		"default_poll_hours_cron": {
			Platform:   scheduler.PlatformCron,
			BinaryPath: "/usr/local/bin/symeraseme",
			ProjectDir: "/srv/erase",
			TickHour:   10,
			TickMinute: 0,
		},
		"venv_activate_cron": {
			Platform:     scheduler.PlatformCron,
			BinaryPath:   "/usr/local/bin/symeraseme",
			ProjectDir:   "/srv/erase",
			TickHour:     10,
			PollHours:    []int{8, 20},
			VenvActivate: "/srv/erase/venv/bin/activate with spaces'and'quotes",
		},
	}

	caseNames := make([]string, 0, len(cases))
	for name := range cases {
		caseNames = append(caseNames, name)
	}
	sort.Strings(caseNames)

	legacyContent := map[string]string{
		"go_wrapper_not_flagged": "#!/usr/bin/env bash\n# Generated by symeraseme generate-scheduler (Go)\nexec '/tmp/symeraseme' tick\n",
		"legacy_marker_no_go_suffix": "ExecStart=/bin/bash /home/me/.venv/bin/python\n" +
			"# Generated by symeraseme generate-scheduler\n",
		"python_keyword_only":            "python3 -m symeraseme",
		"case_insensitive_python_marker": "PYTHON3 -m symeraseme",
		"native_content_no_markers":      "native symeraseme",
		"site_packages_marker":           "/usr/lib/site-packages/symeraseme",
		"symeraseme_core_scheduler_marker": "from symeraseme.core.scheduler " +
			"import run",
		"uv_run_marker":           "uv run symeraseme tick",
		"venv_activate_marker":    "source venv/bin/activate\nsymeraseme tick\n",
		"legacy_marker_no_python": "# Generated by symeraseme generate-scheduler\nexec symeraseme\n",
		"empty_content":           "",
		// strings.ToLower folds U+0130 (LATIN CAPITAL LETTER I WITH DOT
		// ABOVE) to plain "i" via Go's simple (always-one-rune) case
		// mapping, so this still matches the venv/bin/activate marker.
		"turkish_dotted_i_marker": "ExecStart=/bin/bash VENV/BİN/ACTIVATE\n",
	}
	legacyNames := make([]string, 0, len(legacyContent))
	for name := range legacyContent {
		legacyNames = append(legacyNames, name)
	}
	sort.Strings(legacyNames)

	output := oracleOutput{
		Provenance: provenance{
			SourceRevision: sourceRevision,
			SourcePath:     "internal/scheduler/scheduler.go",
			SourceSHA256:   sourceSHA256,
			Schema:         oracleSchema,
		},
		Cases:       make(map[string]map[string]string, len(caseNames)),
		LegacyCases: make(map[string]legacyCaseResult, len(legacyNames)),
	}
	for _, name := range caseNames {
		files, err := scheduler.Generate(cases[name])
		if err != nil {
			fatal(fmt.Sprintf("generate case %s: %v", name, err))
		}
		output.Cases[name] = files
	}

	legacyDir, err := os.MkdirTemp("", "symeraseme-legacy-oracle-*")
	if err != nil {
		fatal(fmt.Sprintf("create legacy case temp dir: %v", err))
	}
	defer os.RemoveAll(legacyDir)
	for _, name := range legacyNames {
		content := legacyContent[name]
		path := filepath.Join(legacyDir, name+".unit")
		if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
			fatal(fmt.Sprintf("write legacy case %s: %v", name, err))
		}
		isPython, err := scheduler.DetectLegacyPythonUnit(path)
		if err != nil {
			fatal(fmt.Sprintf("detect legacy case %s: %v", name, err))
		}
		output.LegacyCases[name] = legacyCaseResult{Content: content, IsPython: isPython}
	}

	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(output); err != nil {
		fatal("write oracle result")
	}
}

// runtimeCaller is kept as a variable so source paths can be tested without
// modifying tracked source files.
var runtimeCaller = func() (uintptr, string, int, bool) {
	return runtime.Caller(0)
}

func oracleSourcePath() string {
	_, source, _, ok := runtimeCaller()
	if !ok {
		fatal("oracle source path unavailable")
	}
	return source
}

func verifySourceHash(path, expected string) error {
	contents, err := os.ReadFile(path)
	if err != nil {
		return err
	}
	digest := sha256.Sum256(contents)
	if hex.EncodeToString(digest[:]) != expected {
		return fmt.Errorf("source hash mismatch")
	}
	return nil
}

func fatal(message string) {
	fmt.Fprintln(os.Stderr, message)
	os.Exit(1)
}
