"""Generate the golden tick fixture for the Go port's #715 conformance test.

Builds a synthetic but realistic request set (one per tick status:
AWAITING_ACK reminder due, AWAITING_RESPONSE deadline passed, OVERDUE
DPA escalation due, CONFIRMED re-scan due) with deterministic UTC
timestamps anchored at a fixed reference date, then runs the REAL Python
run_tick() and dumps the actions as JSON for the Go port to replay.

Usage: .venv/bin/python scripts/gen_golden_tick_fixture.py
"""
from __future__ import annotations

import json
import os
import shutil
import sys

import keyring
from keyring.backend import KeyringBackend

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK = "/tmp/golden-tick-data"
REGISTRY = "/tmp/golden-plan-registry"
NOW = "2026-08-27T10:00:00+00:00"


class InMemoryKeyring(KeyringBackend):
    def __init__(self) -> None:
        self._store: dict[tuple[str, str], str] = {}

    @property
    def priority(self) -> float:
        return 1_000_000

    def get_password(self, service, username):
        return self._store.get((service, username))

    def set_password(self, service, username, password):
        self._store[(service, username)] = password

    def delete_password(self, service, username):
        self._store.pop((service, username), None)


def iso(offset_days: int) -> str:
    from datetime import UTC, datetime, timedelta

    return (datetime.fromisoformat(NOW) + timedelta(days=offset_days)).astimezone(UTC).isoformat()


def main() -> int:
    if os.path.exists(WORK):
        shutil.rmtree(WORK)
    os.makedirs(WORK, exist_ok=True)
    os.environ["SYMERASEME_RESOURCES"] = REGISTRY
    os.environ["SYMERASEME_DATA_DIR"] = WORK
    os.environ["SYMERASEME_IDENTITY_PATH"] = os.path.join(WORK, "identity.enc")
    keyring.set_keyring(InMemoryKeyring())

    sys.path.insert(0, os.path.join(REPO, "src"))
    from symeraseme.core.db_connection import close_connection, init_db
    from symeraseme.core.deadlines import run_tick
    from symeraseme.core.events import create_campaign, create_removal_request
    from symeraseme.core.projection import append_event_and_project, rebuild_all_states

    init_db()
    try:
        create_campaign("golden-tick", kind="initial")
        # campaign_id, jurisdiction, channel, template
        plan = [
            # (id, broker, jurisdiction)
            ("broker-a", "GDPR"),
            ("broker-b", "GDPR"),
            ("broker-c", "GDPR"),
            ("broker-d", "GDPR"),
        ]
        # Create removal requests and replay a realistic tick history.
        # occurred_at offsets are relative to NOW (days).
        # R1: AWAITING_ACK, second reminder due (sent -21d, one reminder -14d)
        # R2: AWAITING_RESPONSE, deadline passed (sent -40d, verification -38d)
        # R3: OVERDUE, DPA escalation due (sent -50d, deadline reached -20d)
        # R4: CONFIRMED, re-scan due (sent -100d, ack -98d, confirmed -98d)
        histories = [
            ("broker-a", "GDPR", [
                ("SENT", {"expected_response_days": 30}, -21),
                ("REMINDER_SENT", {"count": 1, "days_since_sent": 14}, -14),
            ]),
            ("broker-b", "GDPR", [
                ("SENT", {"expected_response_days": 30}, -40),
                ("VERIFICATION_PROVIDED", {}, -38),
            ]),
            ("broker-c", "GDPR", [
                ("SENT", {"expected_response_days": 30}, -50),
                ("DEADLINE_REACHED", {"deadline_days": 30}, -20),
            ]),
            ("broker-d", "GDPR", [
                ("SENT", {"expected_response_days": 30}, -100),
                ("ACK", {"message_id": "m-1"}, -98),
                ("CONFIRMED", {"via": "ack"}, -98),
            ]),
        ]
        for broker_id, jurisdiction, hist in histories:
            rid = create_removal_request(
                broker_id=broker_id,
                channel="email",
                campaign_id="golden-tick",
                jurisdiction=jurisdiction,
            )
            for event_type, payload, offset_days in hist:
                append_event_and_project(
                    rid,
                    event_type,
                    payload=payload,
                    source="system",
                    occurred_at=iso(offset_days),
                )

        rebuild_all_states()

        from datetime import UTC, datetime

        actions = run_tick(reference_date=datetime.fromisoformat(NOW))
        out = {
            "fixture": "golden-tick (generated by Python " + sys.version.split()[0] + ")",
            "now": NOW,
            "actions": [
                {
                    "request_id": a.request_id,
                    "broker_id": a.broker_id,
                    "campaign_id": a.campaign_id,
                    "current_status": a.current_status,
                    "action_type": a.action_type,
                    "event_type": a.event_type,
                    "description": a.description,
                    "payload": dict(a.payload),
                    "dry_run": a.dry_run,
                }
                for a in actions
            ],
        }
        path = os.path.join(REPO, "tests", "fixtures", "event-store", "golden-tick.json")
        with open(path, "w") as f:
            json.dump(out, f, indent=2, sort_keys=True)
        print(json.dumps(out, indent=2, sort_keys=True)[:4000])
        print("WROTE", path)
        return 0
    finally:
        close_connection()


if __name__ == "__main__":
    raise SystemExit(main())