"""Generate the golden plan-fixture for the Go port's #714 conformance test.

Runs the REAL Python planning path (plan_campaign → repositories →
event store) against a fixed mini-registry and dumps the resulting
removal_requests + PLANNED event payloads as JSON.  The Go port test
replays the same registry + inputs and must produce byte-identical rows.

Usage: .venv/bin/python scripts/gen_golden_plan_fixture.py
"""
from __future__ import annotations

import json
import os
import shutil
import sqlite3
import sys

import keyring
from keyring.backend import KeyringBackend

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
WORK = "/tmp/golden-plan-data"
REGISTRY = "/tmp/golden-plan-registry"


class InMemoryKeyring(KeyringBackend):
    def __init__(self) -> None:
        self._store: dict[tuple[str, str], str] = {}

    @property
    def priority(self) -> float:
        return 1_000_000

    def get_password(self, service, username):
        return self._store.get((service, username))

    def set_password(self, service, username, password):
        self._store[(service, username)] = password

    def delete_password(self, service, username):
        self._store.pop((service, username), None)


def main() -> int:
    if os.path.exists(WORK):
        shutil.rmtree(WORK)
    os.makedirs(WORK, exist_ok=True)
    os.environ["SYMERASEME_RESOURCES"] = REGISTRY
    os.environ["SYMERASEME_DATA_DIR"] = WORK
    os.environ["SYMERASEME_IDENTITY_PATH"] = os.path.join(WORK, "identity.enc")
    keyring.set_keyring(InMemoryKeyring())

    sys.path.insert(0, os.path.join(REPO, "src"))
    from symeraseme.core.db_connection import close_connection, init_db
    from symeraseme.core.planning import plan_campaign
    from symeraseme.core.repositories.requests import list_removal_requests

    init_db()
    try:
        result = plan_campaign(campaign_id="golden-plan", max_brokers=30)
        reqs = list_removal_requests(campaign_id="golden-plan")
        conn = sqlite3.connect(os.path.join(WORK, "symeraseme.db"))
        cur = conn.execute(
            "SELECT request_id, event_type, payload_json, source FROM request_events "
            "WHERE event_type = 'PLANNED' ORDER BY id"
        )
        events = [
            {
                "request_id": r,
                "event_type": e,
                "source": s,
                "payload": json.loads(p),
            }
            for r, e, p, s in cur.fetchall()
        ]
        conn.close()

        out = {
            "fixture": "golden-plan (generated by Python " + sys.version.split()[0] + ")",
            "campaign_id": result["campaign_id"],
            "total_brokers": result["total_brokers"],
            "matched": result["matched"],
            "planned": result["planned"],
            "plan_requests": [
                {k: (str(v) if k == "request_id" else v) for k, v in r.items()}
                for r in result["requests"]
            ],
            "db_requests": [
                {
                    "id": r["id"],
                    "broker_id": r["broker_id"],
                    "channel": r["channel"],
                    "campaign_id": r["campaign_id"],
                    "jurisdiction": r["jurisdiction"],
                    "template_id": r["template_id"],
                    "identity_snapshot_hash": r["identity_snapshot_hash"],
                }
                for r in reqs
            ],
            "events": events,
        }
        path = os.path.join(REPO, "tests", "fixtures", "event-store", "golden-plan.json")
        with open(path, "w") as f:
            json.dump(out, f, indent=2, sort_keys=True)
        print(json.dumps(out, indent=2, sort_keys=True)[:4000])
        print("WROTE", path)
        return 0
    finally:
        close_connection()


if __name__ == "__main__":
    raise SystemExit(main())