use super::{Config, poll_wrapper, wrapper};
use std::collections::BTreeMap;
use std::fmt::Write as _;

pub(super) fn generate(
    cfg: &Config,
    binary_path: &str,
    project_dir: &str,
    poll_hours: &[i32],
) -> BTreeMap<String, String> {
    let mut files = BTreeMap::new();
    files.insert(
        "symeraseme-tick.sh".to_string(),
        wrapper(
            &[binary_path, "tick", "--output", "json"],
            project_dir,
            &cfg.venv_activate,
        ),
    );
    files.insert(
        "symeraseme-poll.sh".to_string(),
        poll_wrapper(binary_path, project_dir, &cfg.venv_activate, poll_hours),
    );
    files.insert(
        "symeraseme-rescan.sh".to_string(),
        wrapper(
            &[binary_path, "tick", "--output", "json", "--dry-run"],
            project_dir,
            &cfg.venv_activate,
        ),
    );
    files.insert("install.sh".to_string(), install_script());
    files.insert("uninstall.sh".to_string(), uninstall_script());
    files.insert(
        "crontab.txt".to_string(),
        cron_tab(cfg.tick_hour, cfg.tick_minute),
    );
    files
}

fn cron_tab(hour: i32, minute: i32) -> String {
    let mut text = String::new();
    write!(
        text,
        "# Symaira EraseMe scheduled tasks\n\
         # Generated by symeraseme generate-scheduler (Go)\n\
         \n\
         # Tick (daily at {hour:02}:{minute:02})\n\
         {minute} {hour} * * * {{wrapper_dir}}/symeraseme-tick.sh\n\
         \n\
         # Poll inbox (hourly wrapper checks configured times)\n\
         0 * * * * {{wrapper_dir}}/symeraseme-poll.sh\n\
         \n\
         # Re-scan (quarterly on 1st of Jan, Apr, Jul, Oct)\n\
         {minute} {hour} 1 1,4,7,10 * {{wrapper_dir}}/symeraseme-rescan.sh\n\
         \n\
         # End Symaira EraseMe scheduled tasks\n"
    )
    .expect("writing to a String never fails");
    text
}

fn block_removal_script() -> &'static str {
    "awk '\n  \
     /^# Symaira EraseMe scheduled tasks$/ { skip=1; next }\n  \
     /^# End Symaira EraseMe scheduled tasks$/ { skip=0; next }\n  \
     skip { next }\n  \
     { print }\n\
     '"
}

fn install_script() -> String {
    format!(
        "#!/usr/bin/env bash\n\
         set -euo pipefail\n\
         SCRIPT_DIR=\"$(cd \"$(dirname \"$0\")\" && pwd)\"\n\
         chmod +x \"$SCRIPT_DIR\"/*.sh\n\
         TEMP=$(mktemp)\n\
         trap 'rm -f \"$TEMP\"' EXIT\n\
         (crontab -l 2>/dev/null || true) | {} > \"$TEMP\"\n\
         sed \"s|{{wrapper_dir}}|$SCRIPT_DIR|g\" \"$SCRIPT_DIR/crontab.txt\" >> \"$TEMP\"\n\
         crontab \"$TEMP\"\n\
         printf 'Crontab installed. Wrappers in: %s\\n' \"$SCRIPT_DIR\"\n",
        block_removal_script()
    )
}

fn uninstall_script() -> String {
    format!(
        "#!/usr/bin/env bash\n\
         set -euo pipefail\n\
         TEMP=$(mktemp)\n\
         trap 'rm -f \"$TEMP\"' EXIT\n\
         (crontab -l 2>/dev/null || true) | {} > \"$TEMP\"\n\
         crontab \"$TEMP\"\n\
         printf '%s\\n' 'Symaira EraseMe entries removed from crontab.'\n",
        block_removal_script()
    )
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn cron_tab_matches_exact_go_layout() {
        assert_eq!(
            cron_tab(6, 45),
            "# Symaira EraseMe scheduled tasks\n\
             # Generated by symeraseme generate-scheduler (Go)\n\
             \n\
             # Tick (daily at 06:45)\n\
             45 6 * * * {wrapper_dir}/symeraseme-tick.sh\n\
             \n\
             # Poll inbox (hourly wrapper checks configured times)\n\
             0 * * * * {wrapper_dir}/symeraseme-poll.sh\n\
             \n\
             # Re-scan (quarterly on 1st of Jan, Apr, Jul, Oct)\n\
             45 6 1 1,4,7,10 * {wrapper_dir}/symeraseme-rescan.sh\n\
             \n\
             # End Symaira EraseMe scheduled tasks\n"
        );
    }
}
