//go:build storage_oracle

// Command storage is the test-only Go provenance oracle for the SQLite
// DB-001..DB-003 contract. It emits JSON only on stdout.
//
// The golden database was generated by the archived Python implementation,
// not by Go. Before it reports Go observations, this command verifies both
// archive blobs from the immutable Python and Go revisions plus the matching
// current worktree fixture/source bytes. A shallow checkout without that local
// history fails closed rather than silently relabelling provenance.
package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"runtime"
	"sort"
	"strings"

	"github.com/danieljustus/symaira-eraseme/internal/eventstore"
)

const (
	oracleSchema = "symaira-eraseme.storage-parity.v1"

	// The fixture was first introduced here. The immutable python-final tag
	// below preserves the same generator and fixture blobs.
	fixtureOriginRevision = "993f9a652efd4470985c29b15fff0d8efb8d72c7"
	fixtureArchiveTag     = "python-final"
	fixtureArchiveTagOID  = "9381296d68c7d674b102196f6d6b25a050bd6a66"
	fixtureArchiveCommit  = "538f97070202fb1577db3c81d88ab908bd8671eb"

	fixtureGeneratorPath    = "scripts/generate_event_store_fixture.py"
	fixtureGeneratorGitBlob = "28456fcfe96a27a32ee9be8eeb84089069f49f8e"
	fixtureGeneratorSHA256  = "2dff9a2ab364a4ec80674175fe8731ab9c6061a83960d50b04f184777be82e84"

	fixturePath    = "tests/fixtures/event-store/golden-campaign.db"
	fixtureGitBlob = "83d02232e9c1d146ef55c3cee058c646fe1c8c28"
	fixtureSHA256  = "595a4840dbe6a52324b40778c53016b0c809e01451ba4fa5f20c3fd3447e0120"
	fixtureSize    = 102400

	// This is the last Go revision that changed the storage source. The
	// immutable blob and SHA-256 must also match the current HEAD/worktree.
	goSourceRevision = "18c5dc1109e8824265f862f14584697d08152e40"
	goSourcePath     = "internal/eventstore/store.go"
	goSourceGitBlob  = "2201ac9ffd929f871fbd54f9e7e77eb59749c5a6"
	goSourceSHA256   = "fd1dd416606f29aa4726a62ffe6ad83ef9d7c9eb6c6f42d81e87987913968df3"
)

type provenance struct {
	Schema                  string `json:"schema"`
	GoSourceRevision        string `json:"go_source_revision"`
	GoSourcePath            string `json:"go_source_path"`
	GoSourceGitBlob         string `json:"go_source_git_blob"`
	GoSourceSHA256          string `json:"go_source_sha256"`
	FixtureOriginRevision   string `json:"fixture_origin_revision"`
	FixtureArchiveTag       string `json:"fixture_archive_tag"`
	FixtureArchiveTagOID    string `json:"fixture_archive_tag_oid"`
	FixtureArchiveCommit    string `json:"fixture_archive_commit"`
	FixtureGeneratorPath    string `json:"fixture_generator_path"`
	FixtureGeneratorGitBlob string `json:"fixture_generator_git_blob"`
	FixtureGeneratorSHA256  string `json:"fixture_generator_sha256"`
	FixturePath             string `json:"fixture_path"`
	FixtureGitBlob          string `json:"fixture_git_blob"`
	FixtureSHA256           string `json:"fixture_sha256"`
	FixtureSize             int    `json:"fixture_size"`
}

type pragmaSnapshot struct {
	BusyTimeout int    `json:"busy_timeout"`
	ForeignKeys int    `json:"foreign_keys"`
	JournalMode string `json:"journal_mode"`
}

type schemaEntry struct {
	Type string `json:"type"`
	Name string `json:"name"`
	SQL  string `json:"sql"`
}

type sqliteSnapshot struct {
	UserVersion    int              `json:"user_version"`
	Pragmas        pragmaSnapshot   `json:"pragmas"`
	Schema         []schemaEntry    `json:"schema"`
	TableRowCounts map[string]int64 `json:"table_row_counts"`
}

type oracleOutput struct {
	Provenance provenance     `json:"provenance"`
	Fresh      sqliteSnapshot `json:"fresh"`
	Golden     sqliteSnapshot `json:"golden"`
}

func main() {
	if err := run(); err != nil {
		fmt.Fprintln(os.Stderr, "storage oracle:", err)
		os.Exit(1)
	}
}

func run() error {
	root, err := repositoryRoot()
	if err != nil {
		return err
	}
	output, err := capture(root)
	if err != nil {
		return err
	}
	encoder := json.NewEncoder(os.Stdout)
	encoder.SetIndent("", "  ")
	return encoder.Encode(output)
}

func capture(root string) (oracleOutput, error) {
	provenance, fixture, err := validateProvenance(root)
	if err != nil {
		return oracleOutput{}, err
	}

	temporaryRoot, err := os.MkdirTemp("", "symeraseme-storage-oracle-*")
	if err != nil {
		return oracleOutput{}, fmt.Errorf("create isolated oracle directory: %w", err)
	}
	defer os.RemoveAll(temporaryRoot)

	fresh, err := snapshotStore(filepath.Join(temporaryRoot, "fresh.db"))
	if err != nil {
		return oracleOutput{}, fmt.Errorf("snapshot fresh Go database: %w", err)
	}

	goldenPath := filepath.Join(temporaryRoot, "golden-campaign.db")
	if err := os.WriteFile(goldenPath, fixture, 0o600); err != nil {
		return oracleOutput{}, fmt.Errorf("copy golden fixture for Go open: %w", err)
	}
	golden, err := snapshotStore(goldenPath)
	if err != nil {
		return oracleOutput{}, fmt.Errorf("snapshot Go-opened golden database: %w", err)
	}

	return oracleOutput{Provenance: provenance, Fresh: fresh, Golden: golden}, nil
}

func expectedProvenance() provenance {
	return provenance{
		Schema:                  oracleSchema,
		GoSourceRevision:        goSourceRevision,
		GoSourcePath:            goSourcePath,
		GoSourceGitBlob:         goSourceGitBlob,
		GoSourceSHA256:          goSourceSHA256,
		FixtureOriginRevision:   fixtureOriginRevision,
		FixtureArchiveTag:       fixtureArchiveTag,
		FixtureArchiveTagOID:    fixtureArchiveTagOID,
		FixtureArchiveCommit:    fixtureArchiveCommit,
		FixtureGeneratorPath:    fixtureGeneratorPath,
		FixtureGeneratorGitBlob: fixtureGeneratorGitBlob,
		FixtureGeneratorSHA256:  fixtureGeneratorSHA256,
		FixturePath:             fixturePath,
		FixtureGitBlob:          fixtureGitBlob,
		FixtureSHA256:           fixtureSHA256,
		FixtureSize:             fixtureSize,
	}
}

// validateProvenance validates the immutable archive objects first, then the
// tracked HEAD blobs and current worktree bytes that the oracle will execute.
func validateProvenance(root string) (provenance, []byte, error) {
	if err := validateArchiveTag(root); err != nil {
		return provenance{}, nil, err
	}
	if err := validateImmutableBlob(
		root,
		fixtureOriginRevision,
		fixtureGeneratorPath,
		fixtureGeneratorGitBlob,
		fixtureGeneratorSHA256,
		"fixture-origin generator",
	); err != nil {
		return provenance{}, nil, err
	}
	if err := validateImmutableBlob(
		root,
		fixtureOriginRevision,
		fixturePath,
		fixtureGitBlob,
		fixtureSHA256,
		"fixture-origin golden fixture",
	); err != nil {
		return provenance{}, nil, err
	}
	if err := validateImmutableBlob(
		root,
		fixtureArchiveCommit,
		fixtureGeneratorPath,
		fixtureGeneratorGitBlob,
		fixtureGeneratorSHA256,
		"archived fixture generator",
	); err != nil {
		return provenance{}, nil, err
	}
	if err := validateImmutableBlob(
		root,
		fixtureArchiveCommit,
		fixturePath,
		fixtureGitBlob,
		fixtureSHA256,
		"archived golden fixture",
	); err != nil {
		return provenance{}, nil, err
	}
	if err := validateImmutableBlob(
		root,
		goSourceRevision,
		goSourcePath,
		goSourceGitBlob,
		goSourceSHA256,
		"immutable Go storage source",
	); err != nil {
		return provenance{}, nil, err
	}
	if err := validateHeadBlob(root, goSourcePath, goSourceGitBlob, "Go storage source"); err != nil {
		return provenance{}, nil, err
	}
	if err := validateHeadBlob(root, fixturePath, fixtureGitBlob, "golden fixture"); err != nil {
		return provenance{}, nil, err
	}
	if _, err := validateWorktreeFile(root, goSourcePath, goSourceSHA256, "worktree Go storage source"); err != nil {
		return provenance{}, nil, err
	}
	fixture, err := validateWorktreeFile(root, fixturePath, fixtureSHA256, "worktree golden fixture")
	if err != nil {
		return provenance{}, nil, err
	}
	if len(fixture) != fixtureSize {
		return provenance{}, nil, fmt.Errorf(
			"worktree golden fixture size mismatch: got %d, want %d",
			len(fixture),
			fixtureSize,
		)
	}
	return expectedProvenance(), fixture, nil
}

func validateArchiveTag(root string) error {
	actualTag, err := gitText(root, "rev-parse", fixtureArchiveTag)
	if err != nil {
		return fmt.Errorf("immutable fixture archive tag unavailable: %w", err)
	}
	if actualTag != fixtureArchiveTagOID {
		return fmt.Errorf(
			"immutable fixture archive tag mismatch: got %s, want %s",
			actualTag,
			fixtureArchiveTagOID,
		)
	}
	tagType, err := gitText(root, "cat-file", "-t", fixtureArchiveTagOID)
	if err != nil {
		return fmt.Errorf("immutable fixture archive tag object unavailable: %w", err)
	}
	if tagType != "tag" {
		return fmt.Errorf("immutable fixture archive object has type %q, want tag", tagType)
	}
	archiveCommit, err := gitText(root, "rev-parse", fixtureArchiveTagOID+"^{}")
	if err != nil {
		return fmt.Errorf("immutable fixture archive target unavailable: %w", err)
	}
	if archiveCommit != fixtureArchiveCommit {
		return fmt.Errorf(
			"immutable fixture archive commit mismatch: got %s, want %s",
			archiveCommit,
			fixtureArchiveCommit,
		)
	}
	return nil
}

func validateImmutableBlob(root, revision, path, expectedBlob, expectedSHA256, label string) error {
	object := revision + ":" + path
	actualBlob, err := gitText(root, "rev-parse", object)
	if err != nil {
		return fmt.Errorf("immutable %s blob unavailable: %w", label, err)
	}
	if actualBlob != expectedBlob {
		return fmt.Errorf("immutable %s blob mismatch: got %s, want %s", label, actualBlob, expectedBlob)
	}
	contents, err := gitBytes(root, "show", object)
	if err != nil {
		return fmt.Errorf("immutable %s contents unavailable: %w", label, err)
	}
	if err := validatePinnedSHA256("immutable "+label, contents, expectedSHA256); err != nil {
		return err
	}
	return nil
}

func validateHeadBlob(root, path, expectedBlob, label string) error {
	actualBlob, err := gitText(root, "rev-parse", "HEAD:"+path)
	if err != nil {
		return fmt.Errorf("tracked %s blob unavailable: %w", label, err)
	}
	if actualBlob != expectedBlob {
		return fmt.Errorf("tracked %s blob mismatch: got %s, want %s", label, actualBlob, expectedBlob)
	}
	return nil
}

func validateWorktreeFile(root, path, expectedSHA256, label string) ([]byte, error) {
	contents, err := os.ReadFile(filepath.Join(root, filepath.FromSlash(path)))
	if err != nil {
		return nil, fmt.Errorf("read %s: %w", label, err)
	}
	if err := validatePinnedSHA256(label, contents, expectedSHA256); err != nil {
		return nil, err
	}
	return contents, nil
}

func validatePinnedSHA256(label string, contents []byte, expected string) error {
	actual := sha256.Sum256(contents)
	if hex.EncodeToString(actual[:]) != expected {
		return fmt.Errorf("%s SHA-256 mismatch", label)
	}
	return nil
}

func snapshotStore(path string) (snapshot sqliteSnapshot, resultErr error) {
	store, err := eventstore.Open(path)
	if err != nil {
		return sqliteSnapshot{}, err
	}
	defer func() {
		if closeErr := store.Close(); resultErr == nil && closeErr != nil {
			resultErr = closeErr
		}
	}()

	database := store.DB()
	if err := database.QueryRow("PRAGMA user_version").Scan(&snapshot.UserVersion); err != nil {
		return sqliteSnapshot{}, fmt.Errorf("read user_version: %w", err)
	}
	if err := database.QueryRow("PRAGMA busy_timeout").Scan(&snapshot.Pragmas.BusyTimeout); err != nil {
		return sqliteSnapshot{}, fmt.Errorf("read busy_timeout: %w", err)
	}
	if err := database.QueryRow("PRAGMA foreign_keys").Scan(&snapshot.Pragmas.ForeignKeys); err != nil {
		return sqliteSnapshot{}, fmt.Errorf("read foreign_keys: %w", err)
	}
	if err := database.QueryRow("PRAGMA journal_mode").Scan(&snapshot.Pragmas.JournalMode); err != nil {
		return sqliteSnapshot{}, fmt.Errorf("read journal_mode: %w", err)
	}

	schema, err := snapshotSchema(store)
	if err != nil {
		return sqliteSnapshot{}, err
	}
	snapshot.Schema = schema

	counts, err := snapshotTableRowCounts(store)
	if err != nil {
		return sqliteSnapshot{}, err
	}
	snapshot.TableRowCounts = counts
	return snapshot, nil
}

func snapshotSchema(store *eventstore.Store) ([]schemaEntry, error) {
	rows, err := store.DB().Query(`SELECT type, name, sql
		FROM sqlite_master
		WHERE sql IS NOT NULL
		ORDER BY type, name`)
	if err != nil {
		return nil, fmt.Errorf("query SQLite schema: %w", err)
	}
	defer rows.Close()

	entries := make([]schemaEntry, 0)
	for rows.Next() {
		var entry schemaEntry
		if err := rows.Scan(&entry.Type, &entry.Name, &entry.SQL); err != nil {
			return nil, fmt.Errorf("read SQLite schema row: %w", err)
		}
		entry.SQL = strings.Join(strings.Fields(entry.SQL), " ")
		entries = append(entries, entry)
	}
	if err := rows.Err(); err != nil {
		return nil, fmt.Errorf("iterate SQLite schema: %w", err)
	}
	return entries, nil
}

func snapshotTableRowCounts(store *eventstore.Store) (map[string]int64, error) {
	tables := []string{"campaigns", "removal_requests", "request_events", "request_state"}
	sort.Strings(tables)
	counts := make(map[string]int64, len(tables))
	for _, table := range tables {
		var count int64
		if err := store.DB().QueryRow("SELECT COUNT(*) FROM " + table).Scan(&count); err != nil {
			return nil, fmt.Errorf("count %s rows: %w", table, err)
		}
		counts[table] = count
	}
	return counts, nil
}

func repositoryRoot() (string, error) {
	_, source, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("oracle source path unavailable")
	}
	directory, err := filepath.Abs(filepath.Dir(source))
	if err != nil {
		return "", fmt.Errorf("resolve oracle source directory: %w", err)
	}
	for {
		if fileExists(filepath.Join(directory, "go.mod")) &&
			fileExists(filepath.Join(directory, filepath.FromSlash(goSourcePath))) {
			return directory, nil
		}
		parent := filepath.Dir(directory)
		if parent == directory {
			return "", fmt.Errorf("repository root not found from oracle source")
		}
		directory = parent
	}
}

func fileExists(path string) bool {
	info, err := os.Stat(path)
	return err == nil && !info.IsDir()
}

func gitText(root string, args ...string) (string, error) {
	output, err := gitBytes(root, args...)
	if err != nil {
		return "", err
	}
	return strings.TrimSpace(string(output)), nil
}

func gitBytes(root string, args ...string) ([]byte, error) {
	commandArgs := append([]string{"-C", root}, args...)
	command := exec.Command("git", commandArgs...)
	output, err := command.Output()
	if err == nil {
		return output, nil
	}
	if exitError, ok := err.(*exec.ExitError); ok {
		return nil, fmt.Errorf("git %s: %w: %s", strings.Join(args, " "), err, strings.TrimSpace(string(exitError.Stderr)))
	}
	return nil, fmt.Errorf("git %s: %w", strings.Join(args, " "), err)
}
